<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/css/lightbox.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/css/contrato-gog/add.css" type="text/css" />
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/js/lightbox.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/js/contrato-gog/add.js"></script>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Cadastrar Contrato GOG
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <form role="form" onSubmit="return validaCadastroContratoGog(this);" name="addContratoGog" id="addContratoGog" enctype="multipart/form-data">
                        <div id="dataTables-example_wrapper2" class="dataTables_wrapper form-inline" role="grid">
                            <div class="row">
                                <div class="col-sm-12">
                                    <input class="form-control" id="nm_contrato_gog" name="nm_contrato_gog" placeholder="Nome">
                                </div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <input type="file" class="lk_contrato_gog" name="lk_contrato_gog" style="display: none;" onChange="Handlechange();" id="pdf_file">
                                    <input type="button" value="Click para selecionar" id="fakeBrowse" onclick="HandleBrowseClick();"/>
                                    <label id="fileLabel">Escolha um arquivo PDF</label>
                                </div>
                                <div class="col-sm-6">
                                    <input class="form-control" id="nu_meses" name="nu_meses" placeholder="Números de meses de validade">
                                </div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group input-group" style="width: 376px !important;">
                                        <span class="input-group-addon" style="float: left; height: 34px; width: 40px;">R$</span>
                                        <input style="float: left !important; width: 89%;" class="form-control" id="nu_valor" type="text" name="nu_valor" placeholder="Valor do Contrato" onkeypress="return validaTeclado(this, event, '999.999,99');" onkeyup="maskIt(this, event, '999.999,99', true)" onfocus="setFieldPosition(this)">
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <input class="form-control" id="nu_dependentes" name="nu_dependentes" placeholder="Números de dependentes">
                                </div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <input type="file" class="lk_img_contrato_gog" name="lk_img_contrato_gog" style="display: none;" onChange="Handlechange2();" id="pdf_file2">
                                    <input type="button" value="Click para selecionar" id="fakeBrowse2" onclick="HandleBrowseClick2();"/>
                                    <label id="fileLabel2">Escolha uma imagem</label>
                                </div>
                                <div class="col-sm-6">
                                    <textarea name="tx_contrato_gog" class="form-control" placeholder="Fale sobre sobre o contrato" style="resize: none;" rows="3"></textarea>
                                </div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="row">
                                <div class="col-sm-6" id="content-select">
                                    <div class="content-select">
                                        <div class="content-procedimento">
                                            <?php foreach ($this->dataProcedimento as $value): ?>
                                                <div class="procedimento" id="<?php echo $value["co_seq_procedimento"]; ?>" onclick="procedimentoSelect(this);">
                                                    <?php echo $value["co_seq_procedimento"]; ?>
                                                    <span>
                                                        <?php echo ($value["co_exame"]==null)?($value["co_consulta"]==null)?($value["co_laboratorio"]==null)?:$value["nm_laboratorio"]:$value["nm_consulta"]:$value["nm_exame"]; ?>
                                                    </span>
                                                </div>
                                            <?php endforeach; ?>
                                        </div>
                                        <div class="content-space">&nbsp;</div>
                                    </div>
                                </div>
                                <div class="col-sm-6" id="content-mais">
                                    <a href="javascript:void(0);" class="btn btn-info btn-lg btn-rect" onclick="addProcedimento();" style="float:left; position:absolute; bottom:14px; clear:left">+</a>
                                </div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Código</th>
                                                <th>Nome Procedimento</th>
                                                <th>Ação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr></tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="row">
                                <div class="col-lg-9"></div>
                                <div class="col-lg-3">
                                    <a href="javascript:void(0);" class="btn btn-success btn-lg btn-rect" onclick="submitCadastroContratoGog();">Cadastrar</a>
                                </div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>