<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/css/lightbox.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/css/contrato-gog/edit.css" type="text/css" />
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/js/lightbox.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/js/contrato-gog/edit.js"></script>

<div class="row">
    <div class="col-lg-12">&nbsp;</div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Editar Contrato GOG
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <form role="form" onSubmit="return validaEditarContratoGog(this);" name="editContratoGog" id="editContratoGog" enctype="multipart/form-data">
                        <div id="dataTables-example_wrapper2" class="dataTables_wrapper form-inline" role="grid">
                            <div class="row">
                                <div class="col-sm-12">
                                    <p>Nome</p>
                                    <input class="form-control nm_contrato_gog" name="nm_contrato_gog" value="<?php echo $this->dataContratoGog[0]["nm_contrato_gog"]; ?>" placeholder="Nome Contrato Gog">
                                </div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <p>Contrato PDF</p>
                                    <input type="file" class="lk_contrato_gog" name="lk_contrato_gog" value="<?php echo $this->dataContratoGog[0]["lk_contrato_gog"]; ?>">
                                </div>
                                <div class="col-sm-6">
                                    <p>Imagem Contrato</p>
                                    <input type="file" class="lk_img_contrato_gog" name="lk_img_contrato_gog" value="<?php echo $this->dataContratoGog[0]["lk_img_contrato_gog"]; ?>">
                                </div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p>Nº Meses</p>
                                    <input class="form-control nu_meses" name="nu_meses" value="<?php echo $this->dataContratoGog[0]["nu_meses"]; ?>" placeholder="Números de meses de validade">
                                </div>
                                <div class="col-sm-6">
                                    <p>Valor</p>
                                    <div class="form-group input-group" style="width: 376px !important;">
                                        <span class="input-group-addon" style="float: left; height: 34px; width: 40px;">R$</span>
                                        <input style="float: left !important; width: 87%;" class="form-control nu_valor" type="text" name="nu_valor" value="<?php echo $this->dataContratoGog[0]["nu_valor"]; ?>" placeholder="Valor do contrato gog" onkeypress="return validaTeclado(this, event, '999.999,99');" onkeyup="maskIt(this, event, '999.999,99', true)" onfocus="setFieldPosition(this)"/>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <p>Dependentes</p>
                                    <input class="form-control nu_dependentes" name="nu_dependentes" value="<?php echo $this->dataContratoGog[0]["nu_dependentes"]; ?>" placeholder="Números de dependentes">
                                </div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="col-sm-12">&nbsp;</div>
                            <input type="hidden" name="co_seq_contrato_gog" value="<?php echo $this->dataContratoGog[0]["co_seq_contrato_gog"]; ?>">
                            <div class="row">
                                <div class="col-lg-6">
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/contrato-gog/index" class="btn btn-warning btn-lg btn-rect"><i class="icon-reply"></i>&nbsp;Voltar</a>
                                </div>
                                <div class="col-lg-6">
                                    <a href="javascript:void(0);" style="float: right;" class="btn btn-success btn-lg btn-rect" onclick="submitEditarContratoGog();">Salvar</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>