<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/css/contrato-gog/view.css" type="text/css" />
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/js/contrato-gog/view.js"></script>

<div class="row">
    <div class="col-lg-12">
        <a href="javascript:void(0)" onclick="goBack();" class="btn btn-warning btn-flat btn-rect"><i class="icon-reply"></i>&nbsp;Voltar</a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">&nbsp;</div>
</div>

<div class="menu-contrato-gog">
    <a href="javascript:void(0);" onclick="clickSobre(this);" class="btn btn-flat btn-rect">Sobre</a>
    <a href="javascript:void(0);" onclick="clickPDF(this);" class="btn btn-flat btn-rect">PDF</a>
</div>
<div class="row content-contrato-gog" id="pdf-contrato-gog" xmlns="http://www.w3.org/1999/html">
    <object data="<?php echo $this->baseUrl(); ?>/adm/contrato/<?php echo $this->dataContratoGog["contrato_gog"]["lk_contrato_gog"]; ?>" type="application/pdf" width="100%" height="667px">
        <embed src="<?php echo $this->baseUrl(); ?>/adm/contrato/<?php echo $this->dataContratoGog["contrato_gog"]["lk_contrato_gog"]; ?>" type="application/pdf" />
    </object>
</div>
<div class="row content-contrato-gog" id="sobre-contrato-gog">

    <div class="col-lg-12">&nbsp;</div>

    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Contrato Gog <h4><?php echo $this->dataContratoGog["contrato_gog"]["nm_contrato_gog"]; ?></h4>
            </div>
        </div>
    </div>

    <div class="col-lg-12">
        <div class="well">
            <div class="col-lg-4">
                <p>Validade</p>
                <h4><?php echo $this->dataContratoGog["contrato_gog"]["nu_meses"]; ?></h4>
            </div>
            <div class="col-lg-4">
                <p>Valor</p>
                <h4>R$ <?php  echo number_format($this->dataContratoGog["contrato_gog"]["valor_contrato"],2,",","."); ?></h4>
            </div>
            <div class="col-lg-4">
                <p>Nº Dependentes</p>
                <h4><?php echo $this->dataContratoGog["contrato_gog"]["nu_dependentes"]; ?></h4>
            </div>
            <div class="col-lg-12">&nbsp;</div>
        </div>
    </div>

    <div class="col-lg-12">
        <div class="well">
            <div class="col-lg-12">
                <h4>Texto do Contrato</h4>
                <div>
                    <?php echo $this->dataContratoGog["contrato_gog"]["tx_contrato_gog"]; ?>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-4">&nbsp;</div>
            <div class="col-lg-4"><p style="text-align: center; font-size: 14px;">Procedimentos</p></div>
            <div class="col-lg-4">&nbsp;</div>
        </div>
        <div class="row">
            <?php if(isset($this->dataContratoGog["procedimento"][0]["nu_procedimento"])) :?>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Tipo</th>
                                <th>Nome</th>
                            </tr>
                            </thead>
                            <tbody>
                                <?php $i=0; ?>
                                <?php foreach($this->dataContratoGog["procedimento"] as $value): ?>
                                    <tr>
                                        <td><?php echo $i; ?></td>
                                        <td><?php echo $value["tipo"]; ?></td>
                                        <td><?php echo $value["nome"]; ?></td>
                                    </tr>
                                    <?php $i++; ?>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            <?php else :?>
                <div class="col-lg-6">
                    <p></p>
                    <h4>Não tem procedimentos vinculado...</h4>
                </div>
            <?php endif; ?>
        </div>
        <div class="col-lg-12">&nbsp;</div>
        <div class="col-lg-12">&nbsp;</div>
    </div>


</div>