<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/css/assinatura/signature-pad.css" type="text/css"/>
<script src="<?php echo $this->baseUrl(); ?>/gogs/js/cartao-marq/signature_pad.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/gogs/js/cartao-marq/app.js"></script>

<div id="signature-pad" class="m-signature-pad">
    <div class="m-signature-pad--body">
        <canvas></canvas>
    </div>
    <div class="m-signature-pad--footer">
        <div class="description">Sign above</div>
        <button type="button" class="button clear" data-action="clear">Clear</button>
        <button type="button" class="button save" data-action="save">Save</button>
    </div>
</div>