<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/js/mais-voce/edit.js"></script>

<div class="row">
    <div class="col-lg-12">
        <a href="javascript:void(0)" onclick="goBack();" class="btn btn-warning btn-flat btn-rect"><i class="icon-reply"></i>&nbsp;Voltar</a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">&nbsp;</div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Editar Mais Você
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <form role="form" onSubmit="return validaEditarMaisVoce(this);" name="editMaisVoce" id="editMaisVoce" enctype="multipart/form-data">
                        <div id="dataTables-example_wrapper2" class="dataTables_wrapper form-inline" role="grid">
                            <div class="row">
                                <div class="col-sm-6">
                                    <input class="form-control" id="nm_title" name="nm_title" placeholder="Título" maxlength="80" value="<?php echo $this->dataMaisVoce["nm_title"]; ?>"/>
                                    <input type="hidden" name="co_seq_mais_voce" id="co_seq_mais_voce" value="<?php echo $this->dataMaisVoce["co_seq_mais_voce"]; ?>"/>
                                </div>
                                <div class="col-sm-6">
                                    <input class="form-control" id="nm_code_color" name="nm_code_color" placeholder="Código da Cor(HTML)" maxlength="6" value="<?php echo $this->dataMaisVoce["nm_code_color"]; ?>">
                                </div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <textarea class="form-control" rows="3" id="tx_mais_voce" name="tx_mais_voce" placeholder="Texto do Mais Você..."><?php echo $this->dataMaisVoce["tx_mais_voce"]; ?></textarea>
                                </div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <a href="javascript:void(0);" class="btn btn-success btn-lg btn-rect" onclick="submitEditarMaisVoce();">Salvar</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>