<div class="row">
    <div class="col-lg-12">
        <a href="javascript:void(0)" onclick="goBack();" class="btn btn-warning btn-flat btn-rect"><i class="icon-reply"></i>&nbsp;Voltar</a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">&nbsp;</div>
</div>

<div class="row">

    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Nome do Post <h4><?php echo $this->dataBlog["nm_blog"]; ?></h4>
            </div>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-lg-12">
        <div class="well">
            <div class="col-lg-3">
                <img class="image-home-pop responsive-img" width="100" src="<?php echo $this->baseUrl(); ?>/adm/blog/img/<?php echo $this->dataBlog["lk_img_blog"]; ?>">
            </div>
            <div class="col-lg-9">
                <h4><?php echo $this->dataBlog["tx_blog"]; ?></h4>
            </div>
            <div class="col-lg-12">&nbsp;</div>
            <div class="col-lg-12">&nbsp;</div>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-lg-12">&nbsp;</div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-4">&nbsp;</div>
            <div class="col-lg-4"><p style="text-align: center; font-size: 17px; font-weight: bold;">Assunto</p></div>
            <div class="col-lg-4">&nbsp;</div>
        </div>
        <div class="row">
            <?php if(count($this->dataProcedimentoBlog) > 0) :?>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Tipo</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $i=0; ?>
                            <?php foreach($this->dataProcedimentoBlog as $value): ?>
                                <tr>
                                    <td><?php echo ($value["co_exame"]==0 || $value["co_exame"]=="") ? ($value["co_consulta"]==0 || $value["co_consulta"]=="") ? $value["nm_laboratorio"] : $value["nm_consulta"] : $value["nm_exame"]; ?></td>
                                    <td><?php echo ($value["co_exame"]==0 || $value["co_exame"]=="") ? ($value["co_consulta"]==0 || $value["co_consulta"]=="") ? "Exame Laboratorial" : "Consulta" : "Exame"; ?></td>
                                </tr>
                                <?php $i++; ?>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            <?php else :?>
                <div class="col-lg-6">
                    <p></p>
                    <h4>Não tem assunto vinculado...</h4>
                </div>
            <?php endif; ?>
        </div>
        <div class="col-lg-12">&nbsp;</div>
        <div class="col-lg-12">&nbsp;</div>
    </div>
</div>