<div class="row">
    <div class="row">
        <div class="col-lg-12">
        </div>
    </div>
    <div style="border-bottom: 17px solid #f5f5f5; border-top: 7px solid #f5f5f5; width: 99.4%; margin-left: 5px;">
        <div class="col-lg-12">
            <h3 style="font-family:'Tobago'; margin-top:7px; text-align:center; color:#972a2b; text-shadow: 0 4px 1px #ffffff, 0 -4px 1px #ffffff, -4px 0 1px #ffffff, 4px 0 1px #ffffff;">Finalizado Cadastro</h3>
        </div>
    </div>
    <div class="row" style="height: 97px;">
        <div class="col-lg-12">
            &nbsp;
        </div>
    </div>
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <div style="text-align: center;">
                <h4>Foi enviado um link para o email <a href="<?php echo $this->userRegister->nmEmail; ?>"><?php echo $this->userRegister->nmEmail; ?></a>.</h4>
            </div>
            <div style="text-align: center;">
                <h4>Neste link, o Cliente podera criar uma senha.</h4>
            </div>
        </div>
        <div class="col-lg-2"></div>
    </div>
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <br/>
            <div style="text-align: center;">
                <div style="margin-top: -5px;">Contacte o Cliente, cadastro salvo com sucesso! </div>
                <div style="color: green;"><i class="icon-ok icon-2x"></i></div>
                <div>Clique <a href="<?php echo $this->baseUrl(); ?>/admin/cliente/add">aqui</a> para cadastrar outro, </div>
                <div>Clique <a href="<?php echo $this->baseUrl(); ?>/admin/cliente/">aqui</a> para listar os clientes</div>
                <div>ou</div>
                <div>Clique <a href="<?php echo $this->baseUrl(); ?>/admin/index/">aqui</a> para ir à página de início</div>
            </div>
        </div>
        <div class="col-lg-2"></div>
    </div>
    <div class="row" style="height: 57px;">
        <div class="col-lg-12">
            &nbsp;
        </div>
    </div>
</div>