<div class="row">
    <div class="col-lg-12">
        <a href="javascript:void(0)" onclick="goBack();" class="btn btn-warning btn-flat btn-rect"><i class="icon-reply"></i>&nbsp;Voltar</a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">&nbsp;</div>
</div>

<div class="row">

    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Mais Você: <h4><?php echo $this->dataMaisVoce["nm_title"]; ?></h4>
            </div>
        </div>
    </div>

    <div class="col-lg-12">
        <div class="well">
            <div class="col-lg-4">
                Código da Cor: #<?php echo $this->dataMaisVoce["nm_code_color"]; ?>
            </div>
            <div class="col-lg-8">
                Usuário que registrou: <?php echo $this->dataMaisVoce["nm_usuario"]; ?>
            </div>
            <div class="col-lg-12">&nbsp;</div>
            <div class="col-lg-8">
                <?php echo $this->dataMaisVoce["tx_mais_voce"]; ?>
            </div>
            <div class="col-lg-4"></div>
            <div class="col-lg-12">&nbsp;</div>
            <div class="col-lg-12">&nbsp;</div>
            <div class="col-lg-12">&nbsp;</div>
        </div>
    </div>

</div>