<div class="row">
    <?php if($this->coTipoLogin < 4) :?>
        <div class="col-lg-6">
            <a href="javascript:void(0)" onclick="goBack();" class="btn btn-warning btn-lg btn-rect"><i class="icon-reply"></i>&nbsp;Voltar</a>
        </div>
        <div class="col-lg-6"></div>
    <?php endif; ?>
</div>

<div class="row">
    <div class="col-lg-12"><p>&nbsp;</p></div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div style="float: left; width: 100%; text-align: center;">
            <img src="<?php echo $this->baseUrl(); ?>/adm/temp/img/<?php echo $this->dataCartao["nu_cartao"] ?>.jpg" width="777"/>
        </div>
    </div>
</div>