<div class="row">
    <div class="col-lg-2">
        <a href="javascript:void(0)" onclick="goBack();" class="btn btn-warning btn-flat btn-rect"><i class="icon-reply"></i>&nbsp;Voltar</a>
    </div>
    <div class="col-lg-10"></div>
</div>
<div class="row">
    <div class="col-lg-12"></div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        Lista de Dependentes
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Nome do Dependente</th>
                    <th>Tipo Dependente</th>
                    <th>Ação</th>
                </tr>
                </thead>
                <tbody>
                <?php $i=1; ?>
                <?php foreach($this->dataDependentes as $value): ?>
                    <tr>
                        <td width="5%"><?php echo $i; ?></td>
                        <td width="51%"><?php echo $value["nm_dependente"]; ?></td>
                        <td width="31%"><?php echo $value["nm_tipo_dependente"]; ?></td>
                        <td width="13%">
                            <a href="<?php echo $this->baseUrl(); ?>/admin/dependente/view/id/<?php echo $value["co_seq_dependentes"]; ?>"><i class="icon-eye-open" title="Visualizar"></i></a>&nbsp;&nbsp;
                            <?php if($this->coTipoLogin==1 || $this->coTipoLogin==2 || $this->coTipoLogin==3) :?>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/dependente/edit/id/<?php echo $value["co_seq_dependentes"]; ?>"><i class="icon-edit" title="Editar"></i></a>&nbsp;&nbsp;
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php $i++; ?>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>