<div class="container_12 bot-1">
    <div class="grid_12">
        <h2 style="text-align: center;" class="indent-2">Convênios</h2>
    </div>


    <!-- Lista de convênios -->
    <div class="row_convenio">
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/abet.jpg" height="50px" />
            </p>
            <span style="font-size: 15px;">Associação Brasileira dos Empregados em Telecomunicação</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/allianz.jpg" height="50px" />
            </p>
            <span style="font-size: 15px;">Allianz</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/amil.png" height="50px" />
            </p>
            <span style="font-size: 15px;">Amil</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/asfub.jpg" height="50px" />
            </p>
            <span style="font-size: 15px;">Associação de Servidores </span>
            <br/>
        </div>
    </div>

    <div class="row_convenio">
        <!--div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/assefaz.jpg" height="50px" />
            </p>
            <span style="font-size: 15px;">Associação dos Servidores da Fundação Universidade de Brasília</span>
            <br/>
        </div-->
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/bacen.png" height="70px" />
            </p>
            <span style="font-size: 15px;">Banco Central do Brasil</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/brasil_center.jpg" height="37px" />
            </p>
            <span style="font-size: 15px;">Brasil Center</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/bradesco.png" height="50px" />
            </p>
            <span style="font-size: 15px;">Bradesco</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/caesan.png" height="70px" />
            </p>
            <span style="font-size: 15px;">Caesan</span>
            <br/>
        </div>
    </div>

    <div class="row_convenio">
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/cape_saude.png" height="70px" />
            </p>
            <span style="font-size: 15px;">Capesaúde</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/casembrapa.jpg" height="50px" />
            </p>
            <span style="font-size: 15px;">Casembrapa</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/cassi.jpg" height="50px" />
            </p>
            <span style="font-size: 15px;">Caixa de Assistência dos Funcionários do Banco do Brasil</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/codevasf.jpg" height="40px" />
            </p>
            <span style="font-size: 15px;">Companhia de Desenvolvimento dos Vales do São Francisco e do Parnaíba</span>
            <br/>
        </div>
    </div>

    <div class="row_convenio">
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/conab.jpg" height="55px" />
            </p>
            <span style="font-size: 15px;">Companhia Nacional de Abastecimento</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/e-vida.png" height="60px" />
            </p>
            <span style="font-size: 15px;">E-Vida</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/embratel.png" height="50px" />
            </p>
            <span style="font-size: 15px;">Embratel</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/faceb.png" height="50px" />
            </p>
            <span style="font-size: 15px;">Faceb</span>
            <br/>
        </div>
    </div>

    <div class="row_convenio">
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/fascal.png" height="50px" />
            </p>
            <span style="font-size: 15px;">Fascal</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/fusex.png" height="70px" />
            </p>
            <span style="font-size: 15px;">Fusex</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/gama.png" height="70px" />
            </p>
            <span style="font-size: 15px;">Gama Saúde</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/geap.png" height="60px" />
            </p>
            <span style="font-size: 15px;">Fundação de Seguridade Social</span>
            <br/>
        </div>
    </div>
    <div class="row_convenio">
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/golden_cross.png" height="65px" />
            </p>
            <span style="font-size: 15px;">Golden Cross</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/infraero.jpg" height="65px" />
            </p>
            <span style="font-size: 15px;">Infraero</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/life_empresarial.png" height="65px" />
            </p>
            <span style="font-size: 15px;">Life Empresarial</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/lincx.png" height="60px" />
            </p>
            <span style="font-size: 15px;">Lincx</span>
            <br/>
        </div>
    </div>
    <div class="row_convenio">
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/mediservice.png" height="45px" />
            </p>
            <span style="font-size: 15px;">MediService</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/notredame.png" height="60px" />
            </p>
            <span style="font-size: 15px;">Notredame</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/omint.jpg" height="70px" />
            </p>
            <span style="font-size: 15px;">Omint</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/one_health.jpg" height="60px" />
            </p>
            <span style="font-size: 15px;">One Health</span>
            <br/>
        </div>
    </div>
    <div class="row_convenio">
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/pame.jpg" height="60px" />
            </p>
            <span style="font-size: 15px;">Pame</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/petrobras.png" height="50px" />
            </p>
            <span style="font-size: 15px;">Petrobras</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/plan_assiste.png" height="50px" />
            </p>
            <span style="font-size: 15px;">Plan Assiste</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/proasa.jpg" height="70px" />
            </p>
            <span style="font-size: 15px;">Proasa</span>
            <br/>
        </div>
    </div>
    <div class="row_convenio">
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/postal_saude.png" height="35px" />
            </p>
            <span style="font-size: 15px;">Postal Saúde</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/real_grande.png" height="65px" />
            </p>
            <span style="font-size: 15px;">Real Grandeza</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/serpro.png" height="50px" />
            </p>
            <span style="font-size: 15px;">Serviço Federal de Processamento de Dados</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/stf_med.png" height="50px" />
            </p>
            <span style="font-size: 15px;">Supremo Tribunal Federal</span>
            <br/>
        </div>
    </div>
    <div class="row_convenio">
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/stj_pro_ser.png" height="60px" />
            </p>
            <span style="font-size: 15px;">Superior Tribunal de Justiça</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/stm_plasjmu.png" height="60px" />
            </p>
            <span style="font-size: 15px;">Superior Tribunal Militar</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/telos.jpg" height="50px" />
            </p>
            <span style="font-size: 15px;">Fundação Embratel de Seguridade Social</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/tjdft.png" height="25px" />
            </p>
            <span style="font-size: 15px;">Tribunal da Justiça do Distrito Federal e dos Territórios</span>
            <br/>
        </div>
    </div>
    <div class="row_convenio">
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/tre.jpeg" height="50px" />
            </p>
            <span style="font-size: 15px;">Tribunal Regional Eleitoral (TRE)</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/trf.jpg" height="50px" />
            </p>
            <span style="font-size: 15px;">Tribunal Regional Federal (TRF)</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/trt.png" height="50px" />
            </p>
            <span style="font-size: 15px;">Tribunal Regional do Trabalho (TRT)</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/tst.png" height="65px" />
            </p>
            <span style="font-size: 15px;">Tribunal Superior do Trabalho (TST)</span>
            <br/>
        </div>
    </div>
    <div class="row_convenio">
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/unimed_central_nacional.png" height="50px" />
            </p>
            <span style="font-size: 15px;">Unafisco Saúde (SINDIFISCO)</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/unimed_central_nacional.png" height="50px" />
            </p>
            <span style="font-size: 15px;">Unimed Central Nacional</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/unimed_planalto.png" height="50px" />
            </p>
            <span style="font-size: 15px;">Unimed Planalto</span>
            <br/>
        </div>
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/unimed_seguros.png" height="50px" />
            </p>
            <span style="font-size: 15px;">Unimed Seguros</span>
            <br/>
        </div>
    </div>
    <div class="row_convenio">
        <div class="grid_3">
            <p class="lead">
                <img src="<?php echo $this->baseUrl(); ?>/site/images/convenio/uvtrp.jpg" height="50px" />
            </p>
            <span style="font-size: 15px;">Unimed Vales do Taquari e Rio Pardo/RS</span>
            <br/>
        </div>
        <div class="grid_3">
        </div>
    </div>

    <div class="grid_12 centro" style="margin-top: 50px;">
        <div class="marq-para-vc">
            <span>MARQ <span>Saúde</span></span>&nbsp; <i>(61) 2026-1313</i>
        </div>
    </div>

</div>