<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/js/caixa/add.js"></script>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Cadastro de Caixa
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <form role="form" onSubmit="return validaCadastroCaixa(this);" name="addCaixa" id="addCaixa">
                        <div class="row">
                            <div class="col-lg-6 form-group">
                                <input type="text" class="form-control" name="nm_caixa" placeholder="Nome do Caixa"/>
                            </div>
                            <div class="col-lg-6 form-group">
                                <select class="form-control" name="co_empresa">
                                    <option value="0">Selecione uma empresa...</option>
                                    <?php foreach($this->dataEmpresa as $value) :?>
                                        <option value="<?php echo $value["co_seq_empresa"]; ?>"><?php echo $value["nm_empresa"]; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <a href="javascript:void(0);" style="float: right;" class="btn btn-success btn-lg btn-rect" onclick="submitCadastroCaixa();">Cadastrar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>