<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/js/caixa/edit.js"></script>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Cadastro de Caixa
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <form role="form" onSubmit="return validaEditarCaixa(this);" name="editCaixa" id="editCaixa">
                        <div class="row">
                            <div class="col-lg-6 form-group">
                                <input type="text" class="form-control" value="<?php echo $this->dataCaixa[0]["nm_caixa"]; ?>" name="nm_caixa" placeholder="Nome do Caixa"/>
                            </div>
                            <div class="col-lg-6 form-group">
                                <fieldset disabled="disabled">
                                    <select class="form-control" name="co_empresa">
                                        <option value="0">Selecione uma empresa...</option>
                                        <?php foreach($this->dataEmpresa as $value) :?>
                                            <option <?php if($value["co_seq_empresa"]==$this->dataCaixa[0]["co_empresa"]){echo "selected";} ?> value="<?php echo $value["co_seq_empresa"]; ?>"><?php echo $value["nm_empresa"]; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </fieldset>
                            </div>
                        </div>
                        <input type="hidden" value="<?php echo $this->dataCaixa[0]["co_seq_caixa"]; ?>" name="co_seq_caixa">
                        <div class="row">
                            <div class="col-lg-6">
                                <a href="<?php echo $this->baseUrl(); ?>/admin/caixa/index" class="btn btn-warning btn-flat btn-rect"><i class="icon-reply"></i>&nbsp;Voltar</a>
                            </div>
                            <div class="col-lg-6">
                                <a href="javascript:void(0);" style="float: right;" class="btn btn-success btn-flat btn-rect" onclick="submitEditarCaixa();">Salvar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>