<div class="row">
    <div class="col-lg-12">
        <a href="javascript:void(0)" onclick="goBack();" class="btn btn-warning btn-flat btn-rect"><i class="icon-reply"></i>&nbsp;Voltar</a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">&nbsp;</div>
</div>

<div class="row">

    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Caixa <h4><?php echo $this->dataCaixa[0]["nm_caixa"]; ?></h4>
            </div>
        </div>
    </div>

    <div class="col-lg-12">
        <div class="well">
            <div class="col-lg-4">
                <p>Empresa</p>
                <h4><?php echo $this->dataCaixa[0]["nm_empresa"]; ?></h4>
            </div>
            <div class="col-lg-4">
                <p>Saldo</p>
                <h4><?php echo $this->dataCaixa[0]["nu_saldo"]; ?></h4>
            </div>
            <div class="col-lg-4">
                <p>Número de procedimentos</p>
                <h4><?php echo $this->dataCaixa[0]["nu_procedimento"]; ?></h4>
            </div>
            <div class="col-lg-12">&nbsp;</div>
        </div>
    </div>

    <div class="col-lg-12">
        <div class="well" style="min-height: 90px;">
            <div class="col-lg-6">
                <p>Status Caixa (Quando ativado é nele que será creditado)</p>
                <h4>
                    <?php echo ($this->dataCaixa[0]["st_ativo"]==1)?"<span style='color: #47a447;'>Caixa Ativado</span>":"<span style='color: #f0ad4e;'>Caixa Desativado</span>"; ?>
                </h4>
            </div>
            <div class="col-lg-6">
                <p>Extrato</p>
                <h4>
                    <a href="<?php echo $this->baseUrl(); ?>/admin/caixa/extrato/id/<?php echo $this->dataCaixa[0]["co_seq_caixa"]; ?>" title="Visualizar Extrato">
                        <i class="icon-eye-open"></i>
                    </a>
                </h4>
            </div>
        </div>
    </div>

</div>