<script type="text/javascript">
    $(function(){
        $("#about").css("background-color", "#efefef");
    });
</script>

<article id="about" class="panel">
    <header>
        <h1>Q Saúde</h1>
        <p>O que é?</p>
    </header>
    <div style="color: #363636;">
        teste testetrhevyrt hwrthrth wrth rth rt hrth th qhth q
         hwtrhwrthwrthtwrtrh tr hwtrh rt hth wt htr hwtr hwthth d
    </div>
</article>