<script type="text/javascript">
    $(function(){
        $("#contact").css("background-color", "#efefef");
    });
</script>

<article id="contact" class="panel">
    <header>
        <h2>Contacte-nos</h2>
    </header>
    <form action="#" method="post">
        <div>
            <div class="row">
                <div class="6u 12u$(mobile)">
                    <input type="text" name="nome" placeholder="Nome" />
                </div>
                <div class="6u$ 12u$(mobile)">
                    <input type="text" name="email" placeholder="Email" />
                </div>
                <div class="12u$">
                    <input type="text" name="assunto" placeholder="Assunto" />
                </div>
                <div class="12u$">
                    <textarea name="mensagem" placeholder="Mensagem" rows="8" style="resize: none;"></textarea>
                </div>
                <div class="12u$">
                    <input type="submit" value="Enviar Mensagem" />
                </div>
            </div>
        </div>
    </form>
</article>