<!-- Home -->
<!--?php include_once "home.phtml"; ?-->

<!-- Register -->
<!--?php include_once "register.phtml"; ?-->

<!-- Contact -->
<!--?php include_once "contact.phtml"; ?-->

<!-- About -->
<!--?php include_once "about.phtml"; ?-->

<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/def/js/scripts/index/index.js"></script>
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/def/css/scripts/index/index.css">
<!-- Banner -->
<section id="banner">
    <div class="inner">
        <h2><img src="<?php echo $this->baseUrl(); ?>/def/images/mais_vantagens_white.png" width="417" height="185" /></h2>
        <p>O cartão da sua vida<br />
            <!--site template freebie<br />
            crafted by <a href="http://html5up.net">HTML5 UP</a>.</p-->
        <ul class="actions">
            <li><a href="<?php echo $this->baseUrl(); ?>/simulacao" class="button special">Faça uma simulação</a></li>
        </ul>
    </div>
    <a href="#one" class="more scrolly">Saiba mais</a>
</section>

<!-- One -->
<section id="one" class="wrapper style1 special">
    <div id="dialog_consultas" title="Consultas">
        <?php $i=0; ?>
        <?php foreach($this->dataConsulta as $value): ?>
        <?php if($i==0): ?>
        <div style="float: left; width: 50%;">
            <?php endif; ?>
            <div>
                <?php echo $value["nm_consulta"]; ?>
            </div>
            <?php if($i%14==0 && $i!=0): ?>
        </div>
        <div style="float: left; width: 50%;">
            <?php endif; ?>
            <?php $i++; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div id="dialog_exames" title="Exames Diagnósticos">
        <?php $i=0; ?>
        <?php foreach($this->dataExame as $value): ?>
        <?php if($i==0): ?>
        <div style="float: left; width: 33.3333%;">
            <?php endif; ?>
            <div class="modal-3column">
                <?php echo $value["nm_exame"]; ?>
            </div>
            <?php if($i%60==0 && $i!=0): ?>
        </div>
        <div style="float: left; width: 33.3333%;">
            <?php endif; ?>
            <?php $i++; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div id="dialog_laboratoriais" title="Exames Laboratoriais">
        <?php $i=0; ?>
        <?php foreach($this->dataLaboratorio as $value): ?>
        <?php if($i==0): ?>
        <div style="float: left; width: 33.3333%;">
            <?php endif; ?>
            <div class="modal-3column">
                <?php echo $value["nm_laboratorio"]; ?>
            </div>
            <?php if($i%70==0 && $i!=0): ?>
        </div>
        <div style="float: left; width: 33.3333%;">
            <?php endif; ?>
            <?php $i++; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="inner">
        <header class="major">
            <h2>Serviços Prestados</h2>
            <p>A melhor rede de saúde do Distrito Federal para Você!</p>
        </header>
        <ul class="icons major">
            <?php if(Util_Util::isMobile()): ?>
                <li>
                    <a href="javascript:void(0);" onclick="openServicos(1);">
                        <span class="icon felipe major style1">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="47px" height="47px" viewBox="0 0 21 21">
                                <path fill="#FFFFFF" d="M5.7 15.2c0.3 0.3 1 0.8 1.8 0.8 2.7 0 3.3-2 3.4-3.6 0.2-2.3 0.8-2.2 1.1-2.2 0.7 0 0.9 0.4 0.9 1.1-0.6 0.4-1 1-1 1.7 0 1.1 0.9 2 2 2s2-0.9 2-2-0.9-2-2-2c-0.1 0-0.1 0-0.2 0-0.2-0.9-0.7-1.8-1.8-1.8-1.6 0-2 1.4-2.1 2.9-0.1 2.1-0.8 2.9-2.3 2.9-0.4 0-0.8-0.2-1-0.4-0.6-0.5-0.5-2.3-0.5-2.3 2 0 4-1.8 4.7-4.8l-0.2-0.1c0.3-1.2 0.5-2.6 0.5-3.6 0-1.1-0.3-1.9-1-2.5s-1.5-0.8-2.1-0.8c-0.2-0.3-0.5-0.5-0.9-0.5-0.5 0-1 0.4-1 1s0.4 1 1 1c0.4 0 0.7-0.2 0.8-0.5 0.5 0 1 0.2 1.5 0.6s0.7 0.9 0.7 1.7c0 0.9-0.2 2.2-0.5 3.5l-0.2-0.1c-0.3 1.1-1.3 3.6-3.3 3.6h-1c-2 0-3-2.5-3.3-3.6l-0.2 0.1c-0.3-1.3-0.5-2.6-0.5-3.5 0-0.8 0.2-1.3 0.7-1.7 0.4-0.4 1-0.5 1.5-0.6 0.1 0.3 0.4 0.5 0.8 0.5 0.6 0 1-0.4 1-1s-0.4-1-1-1c-0.4 0-0.7 0.2-0.9 0.5-0.6 0-1.4 0.2-2.1 0.8s-1 1.4-1 2.5c0 1 0.2 2.4 0.5 3.7l-0.2 0.1c0.7 2.9 2.7 4.7 4.7 4.7 0 0-0.1 2.2 0.7 2.9zM14 14c-0.6 0-1-0.4-1-1s0.4-1 1-1 1 0.4 1 1-0.5 1-1 1z"/>
                            </svg>
                        </span>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0);" onclick="openServicos(2);">
                        <span class="icon heart-line-icone major style2">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 670 670" style="enable-background:new 0 0 512 512;" xml:space="preserve" width="47px" height="47px">
                                <g>
                                    <g>
                                        <path d="M376,33c-60.659,0-99.595,42.012-120,79.849C235.595,75.011,196.659,33,136,33C59.037,33,0,95.446,0,178.268    c0,21.61,4.327,41.561,12.294,60.732h114.434l25.854-51.709c5.098-10.166,21.738-10.166,26.836,0L226,280.456l16.582-33.164    c5.098-10.166,21.738-10.166,26.836,0L286,280.456l46.582-93.164c5.098-10.166,21.738-10.166,26.836,0L385.272,239h114.434    C507.673,219.829,512,199.878,512,178.268C512,95.446,452.963,33,376,33z" fill="#FFFFFF"/>
                                    </g>
                                </g>
                                <g>
                                    <g>
                                        <path d="M376,269c-5.684,0-10.869-3.208-13.418-8.291L346,227.545l-46.582,93.164C296.869,325.792,291.684,329,286,329    c-5.684,0-10.869-3.208-13.418-8.291L256,287.545l-16.582,33.164c-5.098,10.166-21.738,10.166-26.836,0L166,227.545    l-16.582,33.164C146.869,265.792,141.684,269,136,269H28.037c30.873,48.574,86.474,94.713,156.024,153.413    c19.526,16.479,40.298,34.014,62.109,52.925c2.827,2.446,6.328,3.662,9.829,3.662s7.002-1.216,9.829-3.662    c21.812-18.911,42.583-36.445,62.109-52.925c69.551-58.7,125.151-104.839,156.024-153.413H376z" fill="#FFFFFF"/>
                                    </g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                            </svg>
                        </span>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0);" onclick="openServicos(3);">
                        <span class="icon flask-icone major style3">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="47px" height="47px" viewBox="0 0 21 21">
                                <path fill="#FFFFFF" d="M2 16h12l-4-8v-7h1v-1h-6v1h1v7l-4 8zM9 1v7.2l1.9 3.8h-5.8l1.9-3.8v-7.2h2z"/>
                            </svg>
                        </span>
                    </a>
                </li>
            <?php else: ?>
                <li>
                    <a href="javascript:void(0);" onclick="openServicos(1);">
                        <span class="icon felipe major style1">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="112px" height="112px" viewBox="0 0 16 16">
                                <path fill="#FFFFFF" d="M5.7 15.2c0.3 0.3 1 0.8 1.8 0.8 2.7 0 3.3-2 3.4-3.6 0.2-2.3 0.8-2.2 1.1-2.2 0.7 0 0.9 0.4 0.9 1.1-0.6 0.4-1 1-1 1.7 0 1.1 0.9 2 2 2s2-0.9 2-2-0.9-2-2-2c-0.1 0-0.1 0-0.2 0-0.2-0.9-0.7-1.8-1.8-1.8-1.6 0-2 1.4-2.1 2.9-0.1 2.1-0.8 2.9-2.3 2.9-0.4 0-0.8-0.2-1-0.4-0.6-0.5-0.5-2.3-0.5-2.3 2 0 4-1.8 4.7-4.8l-0.2-0.1c0.3-1.2 0.5-2.6 0.5-3.6 0-1.1-0.3-1.9-1-2.5s-1.5-0.8-2.1-0.8c-0.2-0.3-0.5-0.5-0.9-0.5-0.5 0-1 0.4-1 1s0.4 1 1 1c0.4 0 0.7-0.2 0.8-0.5 0.5 0 1 0.2 1.5 0.6s0.7 0.9 0.7 1.7c0 0.9-0.2 2.2-0.5 3.5l-0.2-0.1c-0.3 1.1-1.3 3.6-3.3 3.6h-1c-2 0-3-2.5-3.3-3.6l-0.2 0.1c-0.3-1.3-0.5-2.6-0.5-3.5 0-0.8 0.2-1.3 0.7-1.7 0.4-0.4 1-0.5 1.5-0.6 0.1 0.3 0.4 0.5 0.8 0.5 0.6 0 1-0.4 1-1s-0.4-1-1-1c-0.4 0-0.7 0.2-0.9 0.5-0.6 0-1.4 0.2-2.1 0.8s-1 1.4-1 2.5c0 1 0.2 2.4 0.5 3.7l-0.2 0.1c0.7 2.9 2.7 4.7 4.7 4.7 0 0-0.1 2.2 0.7 2.9zM14 14c-0.6 0-1-0.4-1-1s0.4-1 1-1 1 0.4 1 1-0.5 1-1 1z"/>
                            </svg>
                        </span>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0);" onclick="openServicos(2);">
                        <span class="icon heart-line-icone major style2">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve" width="112px" height="112px">
                                <g>
                                    <g>
                                        <path d="M376,33c-60.659,0-99.595,42.012-120,79.849C235.595,75.011,196.659,33,136,33C59.037,33,0,95.446,0,178.268    c0,21.61,4.327,41.561,12.294,60.732h114.434l25.854-51.709c5.098-10.166,21.738-10.166,26.836,0L226,280.456l16.582-33.164    c5.098-10.166,21.738-10.166,26.836,0L286,280.456l46.582-93.164c5.098-10.166,21.738-10.166,26.836,0L385.272,239h114.434    C507.673,219.829,512,199.878,512,178.268C512,95.446,452.963,33,376,33z" fill="#FFFFFF"/>
                                    </g>
                                </g>
                                <g>
                                    <g>
                                        <path d="M376,269c-5.684,0-10.869-3.208-13.418-8.291L346,227.545l-46.582,93.164C296.869,325.792,291.684,329,286,329    c-5.684,0-10.869-3.208-13.418-8.291L256,287.545l-16.582,33.164c-5.098,10.166-21.738,10.166-26.836,0L166,227.545    l-16.582,33.164C146.869,265.792,141.684,269,136,269H28.037c30.873,48.574,86.474,94.713,156.024,153.413    c19.526,16.479,40.298,34.014,62.109,52.925c2.827,2.446,6.328,3.662,9.829,3.662s7.002-1.216,9.829-3.662    c21.812-18.911,42.583-36.445,62.109-52.925c69.551-58.7,125.151-104.839,156.024-153.413H376z" fill="#FFFFFF"/>
                                    </g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                                <g>
                                </g>
                            </svg>
                        </span>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0);" onclick="openServicos(3);">
                        <span class="icon flask-icone major style3">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="112px" height="112px" viewBox="0 0 16 16">
                                <path fill="#FFFFFF" d="M2 16h12l-4-8v-7h1v-1h-6v1h1v7l-4 8zM9 1v7.2l1.9 3.8h-5.8l1.9-3.8v-7.2h2z"/>
                            </svg>
                        </span>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
        <?php if(!Util_Util::isMobile()): ?>
            <ul class="icons major" id="text-servicos">
                <li><span class="servicos">Consultas</span></li>
                <li><span class="servicos">Exames Diagnósticos</span></li>
                <li><span class="servicos">Exames Laboratoriais</span></li>
            </ul>
        <?php endif; ?>
    </div>
</section>

<!-- Two -->
<section id="two" class="wrapper alt style2">
    <?php $i=3; ?>
    <?php foreach($this->dataContratoGog as $key=>$value):?>
        <?php $i++; ?>
        <section class="spotlight">
            <div class="image"><img src="<?php echo $this->baseUrl(); ?>/def/images/<?php echo $value["lk_img_contrato_gog"]; ?>" alt="" /></div><div class="content">
                <h2><?php echo $value["nm_contrato_gog"]; ?> - <?php echo $value["nm_apelido"]; ?><br /></h2>
                <p>
                    <ul class="contrato-gog-desc">
                        <li><i class="icon-check"></i>&nbsp;Sem Carência</li>
                        <li><i class="icon-check"></i>&nbsp;Sem Limite de utilização diária</li>
                        <li><i class="icon-check"></i>&nbsp;Nas Melhores Clínicas e Laboratórios de Brasília</li>
                        <li><i class="icon-check"></i>&nbsp;Consultas, Exames Diagnósticos e Laboratoriais</li>
                        <?php if($value["nu_dependentes"]>0){ ?>
                            <li><i class="icon-check"></i>&nbsp;<?php echo $value["nu_dependentes"]; ?> Dependente<?php echo ($value["nu_dependentes"]>1)?"s":""; ?></li>
                        <?php }else{ ?>

                        <?php } ?>
                    </ul>
                </p>
                <div class="consultar-preco">
                    <!-- a href="javascript:void(0);" onclick="openServicos(<?php echo $i; ?>);" width="177px">Simular Plano</a-->
                    <a href="<?php echo $this->baseUrl(); ?>/simulacao/index/id/<?php echo $value["co_seq_contrato_gog"]; ?>" width="177px">Simular Plano</a>
                </div>
                <div id="dialog_<?php echo $value["nm_contrato_gog"]; ?>" title="Exames Diagnósticos">
                    <div class="close-modal-preco">
                        <a href="javascript:void(0);" onclick="closeServicos(<?php echo $i; ?>);">
                            <i class="icon fa-close"></i>
                        </a>
                    </div>
                    <div class="title-modal-preco">
                        <?php echo $value["nm_contrato_gog"]; ?> - <?php echo $value["nm_apelido"]; ?>
                    </div>
                    <div class="body-modal-preco">
                        <ul>
                            <li>
                                <i class="icon fa-dollar"></i>
                                &nbsp;&nbsp; R$ <?php echo number_format($value["nu_valor"], 2, ',', '.'); ?> reais
                            </li>
                            <li>
                                <i class="icon fa-credit-card"></i>
                                &nbsp;Até 6x sem juros (parcela de R$<?php echo number_format(($value["nu_valor"]/6), 2, ',', '.'); ?> reais)
                            </li>
                            <li>
                                <i class="icon fa-barcode"></i>
                                &nbsp;Podendo pagar também no boleto (6x sem juros)
                            </li>
                        </ul>
                    </div>
                    <div class="btn-comprar-modal-preco">
                        <a href="<?php echo $this->baseUrl(); ?>/cliente/index/id/<?php echo $value["co_seq_contrato_gog"]; ?>">Comprar</a>
                    </div>
                </div>
            </div>
        </section>
    <?php endforeach;?>
    <!--section class="spotlight">
        <div class="image"><img src="<?php echo $this->baseUrl(); ?>/def/images/single.png" alt="" /></div><div class="content">
            <h2>Magna primis lobortis<br />
                sed ullamcorper</h2>
            <p>Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.</p>
        </div>
    </section>
    <section class="spotlight">
        <div class="image"><img src="<?php echo $this->baseUrl(); ?>/def/images/plus.png" alt="" /></div><div class="content">
            <h2>Tortor dolore feugiat<br />
                elementum magna</h2>
            <p>Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.</p>
        </div>
    </section>
    <section class="spotlight">
        <div class="image"><img src="<?php echo $this->baseUrl(); ?>/def/images/master.png" alt="" /></div><div class="content">
            <h2>Augue eleifend aliquet<br />
                sed condimentum</h2>
            <p>Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.</p>
        </div>
    </section-->
</section>

<!-- Three -->
<!--section id="three" class="wrapper style3 special">
    <div class="inner">
        <header class="major">
            <h2>Accumsan mus tortor nunc aliquet</h2>
            <p>Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend<br />
                fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.</p>
        </header>
        <ul class="features">
            <li class="icon fa-paper-plane-o">
                <h3>Arcu accumsan</h3>
                <p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>
            </li>
            <li class="icon fa-laptop">
                <h3>Ac Augue Eget</h3>
                <p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>
            </li>
            <li class="icon fa-code">
                <h3>Mus Scelerisque</h3>
                <p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>
            </li>
            <li class="icon fa-headphones">
                <h3>Mauris Imperdiet</h3>
                <p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>
            </li>
            <li class="icon fa-heart-o">
                <h3>Aenean Primis</h3>
                <p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>
            </li>
            <li class="icon fa-flag-o">
                <h3>Tortor Ut</h3>
                <p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>
            </li>
        </ul>
    </div>
</section-->


