<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/css/lightbox.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/css/prestador/edit.css" type="text/css" />
<script type="text/javascript">
    var procedimentos = [];
    <?php foreach($this->dataPrestadorProcedimento as $value) :?>
        var procedimento = {"id": <?php echo $value["co_seq_procedimento"] ?>, "nome": "<?php echo ($value["co_exame"]==null)?($value["co_consulta"]==null)?($value["co_laboratorio"]==null)?:$value["nm_laboratorio"]:$value["nm_consulta"]:$value["nm_exame"]; ?>", "tipo": "<?php echo ($value["co_exame"]==null)?($value["co_consulta"]==null)?($value["co_laboratorio"]==null)?:"Laboratório":"Consulta":"Exame"; ?>"};
        procedimentos.push(procedimento);
    <?php endforeach; ?>
</script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/js/lightbox.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/js/prestador/edit.js"></script>

<div class="row">
    <div class="col-lg-12">
        <a href="javascript:void(0)" onclick="goBack();" class="btn btn-warning btn-flat btn-rect"><i class="icon-reply"></i>&nbsp;Voltar</a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">&nbsp;</div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Editar Prestador
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <form role="form" onSubmit="return validaEditarPrestador(this);" name="editPrestador" id="editPrestador" enctype="multipart/form-data">
                        <div id="dataTables-example_wrapper2" class="dataTables_wrapper form-inline" role="grid">
                            <div class="row">
                                <div class="col-sm-6">
                                    <input class="form-control" id="nm_prestador" name="nm_prestador" placeholder="Nome" value="<?php echo $this->dataPrestador["nm_prestador"]; ?>"/>
                                    <input type="hidden" name="co_seq_prestador" id="co_seq_prestador" value="<?php echo $this->dataPrestador["co_seq_prestador"]; ?>"/>
                                </div>
                                <div class="col-sm-6">
                                    <input class="form-control" rows="3" id="nm_site" name="nm_site" placeholder="Site do Prestador..." value="<?php echo $this->dataPrestador["nm_site"]; ?>">
                                </div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <textarea class="form-control" rows="3" id="tx_sobre" name="tx_sobre" placeholder="Fale sobre o Prestador..."><?php echo $this->dataPrestador["tx_sobre"]; ?></textarea>
                                </div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="row">
                                <div class="col-sm-6" id="content-select">
                                    <div class="content-select">
                                        <div class="content-procedimento">
                                            <?php foreach ($this->dataProcedimento as $value): ?>
                                                <div class="procedimento" id="<?php echo $value["co_seq_procedimento"]; ?>" onclick="procedimentoSelect(this);">
                                                    <?php echo $value["co_seq_procedimento"]; ?>
                                                    <span>
                                                        <?php echo ($value["co_exame"]==null)?($value["co_consulta"]==null)?($value["co_laboratorio"]==null)?:$value["nm_laboratorio"]:$value["nm_consulta"]:$value["nm_exame"]; ?>
                                                    </span>
                                                    <i style="display: none;"><?php echo ($value["co_exame"]==null)?($value["co_consulta"]==null)?($value["co_laboratorio"]==null)?:"Laboratório":"Consulta":"Exame"; ?></i>
                                                </div>
                                            <?php endforeach; ?>
                                        </div>
                                        <div class="content-space">&nbsp;</div>
                                    </div>
                                </div>
                                <div class="col-sm-6" id="content-mais">
                                    <a href="javascript:void(0);" class="btn btn-info btn-lg btn-rect" onclick="addProcedimento();" style="float:left; position:absolute; bottom:14px; clear:left">+</a>
                                </div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th>Código</th>
                                            <th>Tipo Procedimento</th>
                                            <th>Nome Procedimento</th>
                                            <th>Ação</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr></tr>
                                        <?php foreach ($this->dataPrestadorProcedimento as $value): ?>
                                            <tr class="procedimento-table">
                                                <td width="5%"><?php echo $value["co_procedimento"] ?></td>
                                                <td width="41%"><?php echo ($value["co_exame"]==null)?($value["co_consulta"]==null)?($value["co_laboratorio"]==null)?:"Laboratório":"Consulta":"Exame"; ?></td>
                                                <td width="41%"><?php echo ($value["co_exame"]==null)?($value["co_consulta"]==null)?($value["co_laboratorio"]==null)?:$value["nm_laboratorio"]:$value["nm_consulta"]:$value["nm_exame"]; ?></td>
                                                <td width="13%">
                                                    <a href="<?php echo $this->baseUrl(); ?>/admin/procedimento/view/id/<?php echo $value["co_procedimento"] ?>"><i class="icon-eye-open" title="Visualizar"></i></a>&nbsp;&nbsp;
                                                    <a href="javascript:void(0);" onclick="removeProcedimento(this);" style="color: #d9534f;" title="Excluir"><i class="icon-trash"></i></a>&nbsp;&nbsp;
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <a href="javascript:void(0);" class="btn btn-success btn-lg btn-rect" onclick="submitEditarPrestador();">Salvar</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>