<div class="row">
    <div class="col-lg-12">
        <a href="javascript:void(0)" onclick="goBack();" class="btn btn-warning btn-flat btn-rect"><i class="icon-reply"></i>&nbsp;Voltar</a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">&nbsp;</div>
</div>

<div class="row">

    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Prestador: <h4><?php echo $this->dataPrestador["nm_prestador"]; ?></h4>
            </div>
        </div>
    </div>

    <div class="col-lg-12">
        <div class="well">
            <div class="col-lg-4">
                <img src='<?php echo $this->baseUrl()."/site/images/prestador/".$this->dataPrestador["lk_prestador"]; ?>' height="40" />
            </div>
            <div class="col-lg-8">
                <?php echo $this->dataPrestador["tx_sobre"]; ?>
            </div>
            <div class="col-lg-12">&nbsp;</div>
            <div class="col-lg-12">&nbsp;</div>
            <div class="col-lg-4">
                Site:
            </div>
            <div class="col-lg-8">
                <?php echo $this->dataPrestador["nm_site"]; ?>
            </div>
            <div class="col-lg-12">&nbsp;</div>
        </div>
    </div>

</div>