<div class="container_12 bot-1">
    <div class="grid_12">
        <h2 style="text-align: center;" class="indent-2">Especialidades</h2>
    </div>

    <ul class="list-project">
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/angiologia.jpg" width="225" height="125" alt=""/>
            <h4>Angiologista</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/cardiologia.jpg" width="225" height="125" alt=""/>
            <h4>Cardiologista</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/clinica_medica.jpg" height="125" width="225" alt=""/>
            <h4>Clínica Médica</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/dermatologia.jpg"  height="125" width="225" alt=""/>
            <h4>Dermatologia</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/endocrinologista.jpg" height="125" width="225" alt=""/>
            <h4>Endocrinologista Adulta e Pediátrica</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/endocrinologia_esportiva.jpg" height="125" width="225" alt=""/>
            <h4>Endocrinologista Esportiva</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/fonoaudiologia.jpg" height="125" width="225" alt=""/>
            <h4>Fonoaudiologia</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/geriatria.jpg"  height="125" width="225" alt=""/>
            <h4>Geriatria</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/gineco_obstetrica.jpg"  height="125" width="225" alt=""/>
            <h4>Ginecologia Obstétrica e Oncológica</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/neurologista.jpg" height="125" width="225" alt=""/>
            <h4>Neurologista</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/neuropediatria.jpg" height="125" width="225" alt=""/>
            <h4>Neuropediatria</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/clinica_esportiva.jpg" height="125" width="225" alt=""/>
            <h4>Nutrição Clínica e Esportiva</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/ortopedia.jpg" height="125" width="225" alt=""/>
            <h4>Ortopedia e Traumatologia</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/otorrino.jpg" height="125" width="225" alt=""/>
            <h4>Otorrinolaringologia</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/pediatria.jpg" height="125" width="225" alt=""/>
            <h4>Pediatria</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/pneumologia.jpg" height="125" width="225" alt=""/>
            <h4>Pneumologia</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/psicologia.jpg" height="125" width="225" alt=""/>
            <h4>Psicologia</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/psiquiatria.jpg" height="125" width="225" alt=""/>
            <h4>Psiquiatria</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/reumatologia.jpg" height="125" width="225" alt=""/>
            <h4>Reumatologia</h4>
        </li>
        <li class="grid_3" style="height: 260px;">
            <img src="<?php echo $this->baseUrl(); ?>/site/images/especialidade/urologia.jpg" height="125" width="225" alt=""/>
            <h4>Urologia</h4>
        </li>
    </ul>

    </ul>
    <br/><br/><br/>
    <div class="grid_12 centro" style="margin-top: 50px;">
        <div class="marq-para-vc">
            <span>MARQ <span>Saúde</span></span>&nbsp; <i>(61) 2026-1313</i>
        </div>
    </div>
</div>