<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/css/simulacao/view.css" type="text/css"/>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/js/simulacao/view.js"></script>

<div class="row">
    <div class="col-lg-12">
        <a href="javascript:void(0)" onclick="goBack();" class="btn btn-warning btn-flat btn-rect" style="float: left;"><i class="icon-reply"></i>&nbsp;Voltar</a>
        <a href="javascript:void(0)" onclick="goValidaSimulacao();" class="btn btn-success btn-flat btn-rect" style="float: right;"><i class="icon-check-sign"></i>&nbsp;Validar</a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">&nbsp;</div>
</div>

<div class="row">

    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading col-lg-6">
                Nome do Pretendente <h4><?php echo $this->dataSimulacao["nm_cliente"]; ?></h4>
            </div>
            <div class="col-lg-6">
                <span>Email: </span>
                <h4><?php echo $this->dataSimulacao["nm_email"]; ?></h4>
            </div>
            <div class="col-lg-6">
                <span>Número Telefone: </span>
                <h4><?php echo $this->dataSimulacao["nu_telefone"]; ?></h4>
            </div>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-lg-12">&nbsp;</div>
</div>

<div class="row">

    <div class="col-lg-12">
        <div class="well">
            <div class="col-lg-6">
                <p>Contrato Gog</p>
                <h4><?php echo $this->dataSimulacao["nm_contrato_gog"]; ?></h4>
            </div>
            <div class="col-lg-6">
                <p>Forma Pagamento</p>
                <h4><?php echo $this->dataSimulacao["nm_forma_pagamento"]; ?></h4>
            </div>
            <div class="col-lg-6">
                <p>Número Vezes</p>
                <h4><?php echo $this->dataSimulacao["nu_vezes"]; ?></h4>
            </div>
            <div class="col-lg-6">
                <p>Dia do Simulado</p>
                <h4><?php echo Util_Util::getDataClient($this->dataSimulacao["dt_inclusao_simulacao"]); ?></h4>
            </div>
            <div class="col-lg-12">&nbsp;</div>
            <div class="col-lg-12">&nbsp;</div>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-lg-12">
        <div class="well" style="height: 137px;">
            <form id="validar" method="post" onSubmit="return validaSimulacao(this);">
                <div class="col-lg-1">&nbsp;</div>
                <div class="col-lg-11 form-simulacao">
                    <div class="col-lg-4">
                        <h4>Cliente efetuou o cadastro?</h4>
                    </div>
                    <div class="col-lg-8">
                        <h4>
                            <?php if ($this->dataSimulacao["st_validado"]==2): ?>
                                <input type="radio" name="st_cadastrou" id="st_cadastrou" value="1"> Sim &nbsp;
                                <input type="radio" name="st_cadastrou" id="st_cadastrou" value="2" checked> Não
                            <?php else: ?>
                                <?php if ($this->dataSimulacao["st_cadastrou"]==2): ?>
                                    <input type="radio" name="st_cadastrou" id="st_cadastrou" value="1"> Sim &nbsp;
                                    <input type="radio" name="st_cadastrou" id="st_cadastrou" value="2" checked> Não
                                <?php else: ?>
                                    <input type="radio" name="st_cadastrou" id="st_cadastrou" value="1" checked> Sim &nbsp;
                                    <input type="radio" name="st_cadastrou" id="st_cadastrou" value="2"> Não
                                <?php endif; ?>
                            <?php endif; ?>
                        </h4>
                    </div>
                </div>
                <div class="col-lg-1">&nbsp;</div>
                <div class="col-lg-10 form-simulacao">
                    <?php if ($this->dataSimulacao["st_validado"]==2): ?>
                        <textarea id="tx_sobre_simulacao" placeholder="Deixe alguma observação..."></textarea>
                    <?php else: ?>
                        <?php if ($this->dataSimulacao["tx_sobre_simulacao"]=="" || $this->dataSimulacao["tx_sobre_simulacao"]==NULL): ?>
                            <textarea id="tx_sobre_simulacao" placeholder="Deixe alguma observação..."></textarea>
                        <?php else: ?>
                            <?php echo $this->dataSimulacao["tx_sobre_simulacao"]; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                    <input type="hidden" name="co_seq_simulacao" value="<?php echo $this->dataSimulacao["co_seq_simulacao"]; ?>">
                </div>
                <div class="col-lg-1">&nbsp;</div>
            </form>
        </div>
    </div>

</div>