<section id="contact-page" class="container" xmlns="http://www.w3.org/1999/html" style="background-color: #efefef;">
    <div class="row-fluid">
        <div class="span12">
        </div>
    </div>
    <div class="row-fluid" style="border-bottom: 17px solid #f5f5f5; border-top: 7px solid #f5f5f5;">
        <div class="span12">
            <h3 style="font-family:'Tobago'; margin-top:7px; text-align:center; color:#972a2b; text-shadow: 0 4px 1px #ffffff, 0 -4px 1px #ffffff, -4px 0 1px #ffffff, 4px 0 1px #ffffff;">Finalizado Cadastro</h3>
        </div>
    </div>
    <div class="row-fluid" style="height: 97px;">
        <div class="span12">
            &nbsp;
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2"></div>
        <div class="span8">
            <div style="text-align: center;">
                <h4>Foi enviado um link para o email <a href="<?php echo $this->dataCliente["nm_email"]; ?>"><?php echo $this->dataCliente["nm_email"]; ?></a>.</h4>
            </div>
            <div style="text-align: center;">
                <h4>Nesse link, você podera criar sua senha.</h4>
            </div>
        </div>
        <div class="span2"></div>
    </div>
    <div class="row-fluid">
        <div class="span2"></div>
        <div class="span8">
            <br/>
            <div style="text-align: center;">
                <div>Clique <a href="<?php echo $this->baseUrl(); ?>/index/">aqui</a> para ir à página de início </div>
                <div>ou</div>
                <div style="margin-top: -5px;">logue clicando no ícone &nbsp;<a data-toggle="modal" href="#loginForm"><i class="icon-lock icon-2x"></i></a></div>
            </div>
        </div>
        <div class="span2"></div>
    </div>
    <div class="row-fluid" style="height: 57px;">
        <div class="span12">
            &nbsp;
        </div>
    </div>
</section>