<div class="row">
    <div class="col-lg-12">
        <a href="javascript:void(0)" onclick="goBack();" class="btn btn-warning btn-flat btn-rect"><i class="icon-reply"></i>&nbsp;Voltar</a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">&nbsp;</div>
</div>

<div class="row">

    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Corpo Clínico <h4><?php echo $this->dataCorpoClinico[0]["nm_corpo_clinico"]; ?></h4>
            </div>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-lg-12">
        <div class="well">
            <div class="col-lg-6">
                <p>Tipo Corpo Clínico</p>
                <h4><?php echo $this->dataPrestador[0]["nm_tipo_corpo_clinico"]; ?></h4>
            </div>
            <div class="col-lg-6">
                <p>Número de Login</p>
                <h4><?php echo $this->dataPrestador[0]["nu_login"]; ?></h4>
            </div>
            <div class="col-lg-12">&nbsp;</div>
            <div class="col-lg-12">&nbsp;</div>
        </div>
    </div>

</div>