<html>

<head>
    <meta http-equiv=Content-Type content="text/html; charset=utf-8">
    <meta name=ProgId content=Excel.Sheet>
    <meta name=Generator content="Microsoft Excel 14">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/css/relatorio.css" />
</head>

<body link=blue vlink=purple>
    <div class="content">
        <div class="space">&nbsp;</div>
        <div class="row">
            <?php echo $this->layout()->content; ?>
        </div>
        <div class="space">&nbsp;</div>
    </div>
</body>

</html>
