<?php

	$controller = Zend_Controller_Front::getInstance();
	$controlerName = $controller->getRequest()->getControllerName();
    $actionName = $controller->getRequest()->getActionName();
    $read = Zend_Auth::getInstance()->getStorage()->read();
    $session_login = new Zend_Session_Namespace('Login');
    $isMobile = Util_Util::isMobile();

?>

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="UTF-8" />
    <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3 || $session_login->coTipoLogin==6) :?>
        <title>vantagens admin</title>
    <?php else: ?>
        <title>MarqSaúde Conta</title>
    <?php endif; ?>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
    <link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/site/images/favicon.ico">
    <!-- GLOBAL STYLES -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/plugins/bootstrap/css/bootstrap.mini.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/css/main.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/css/theme.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/css/MoneAdmin.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/plugins/Font-Awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/css/font-awesome.css" />
    <!--END GLOBAL STYLES -->
    <!-- PAGE LEVEL STYLES -->
    <link href="<?php echo $this->baseUrl(); ?>/adm/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/adm/css/layout2.css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/adm/plugins/flot/examples/examples.css" rel="stylesheet" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/plugins/timeline/timeline.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/css/jquery-ui.css" />
    <!-- END PAGE LEVEL  STYLES -->

    <style>
        @font-face{
            font-family:"CenturyGothic";
            src:url('<?php echo $this->baseUrl(); ?>/site/font/CenturyGothicRegular.ttf');
        }
        @font-face{
            font-family:"ERASB";
            src:url('<?php echo $this->baseUrl(); ?>/site/font/ERASB.ttf');
        }
        @font-face{
            font-family:"KGAlwaysAGoodTime";
            src:url('<?php echo $this->baseUrl(); ?>/site/font/KGAlwaysAGoodTime.ttf');
        }
    </style>

    <!-- GLOBAL SCRIPTS -->
    <!--script src="<?php echo $this->baseUrl(); ?>/adm/js/jquery-3.2.1.js"></script-->
    <script src="<?php echo $this->baseUrl(); ?>/adm/js/jquery-2.0.3.min.js"></script>

    <!-- END GLOBAL SCRIPTS -->

    <!-- PAGE LEVEL SCRIPTS -->
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/global.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/site/js/jquery.mask.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/adm/js/jquery-ui.js"></script>
    <!-- END PAGE LEVEL SCRIPTS -->

    <!-- SCRIPTS LIVRE -->
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/js/main.js"></script>
    <!-- END SCRIPTS LIVRE -->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?php echo $this->baseUrl(); ?>/adm/js/html5shiv.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/adm/js/respond.min.js"></script>
    <![endif]-->
</head>

<!-- END HEAD -->

<!-- BEGIN BODY -->
<body class="padTop53 " >

<div class="data" style="display: none">
    <div id="url-page"><?php echo $this->baseUrl(); ?></div>
    <div id="user-type"><?php echo $session_login->coTipoLogin; ?></div>
</div>

<!-- MAIN WRAPPER -->
<div id="wrap" >

    <!-- HEADER SECTION -->
    <div id="top">

        <nav class="navbar navbar-inverse navbar-fixed-top " style="padding-top: 10px;">
            <a data-original-title="Show/Hide Menu" data-placement="bottom" data-tooltip="tooltip" class="accordion-toggle btn btn-primary btn-sm visible-xs" data-toggle="collapse" href="#menu" id="menu-toggle">
                <i class="icon-align-justify"></i>
            </a>
            <!-- LOGO SECTION -->
            <header class="navbar-header">
                <a href="<?php echo $this->baseUrl(); ?>/default/" class="navbar-brand" style="margin-bottom: 10px;">
                    <!--img src="<?php echo $this->baseUrl(); ?>/site/images/logo_q_saude_admin.png" alt="" width="127"/-->
                    <div id="logo_admin"></div>
                </a>
            </header>

            <!-- END LOGO SECTION -->
            <ul class="nav navbar-top-links navbar-right">
                <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2  || $session_login->coTipoLogin==3) :?>
                    <!-- MESSAGES SECTION -->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0);" onclick="clearCount();">
                            <div id="label-success">
                                <?php if( $this->dataContatoN != null && $this->dataContatoN[0]["n"]!=0) :?>
                                    <span class="label label-success">
                                            <?php echo $this->dataContatoN[0]["n"]; ?>
                                    </span>
                                <?php endif; ?>
                            </div>
                            <i class="icon-envelope-alt"></i>&nbsp;
                            <i class="icon-chevron-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-messages" id="dropdown-messages">
                            <?php foreach($this->dataContatoN as $key=>$value) :?>
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/contato/view/id/<?php echo $value["co_seq_contato"] ?>">
                                        <div>
                                            <strong><?php echo $value["nm_nome"]; ?></strong>
                                                <span class="pull-right text-muted">
                                                    <em><?php echo Util_Util::getDataClient($value["dt_inclusao"]); ?></em>
                                                </span>
                                        </div>
                                        <div><?php echo Util_Util::getTextMinBlog($value["tx_mensagem"], 50); ?>
                                        <br />
                                        </div>
                                    </a>
                                </li>
                                <li class="divider"></li>
                            <?php endforeach; ?>
                            <li>
                                <a class="text-center" href="<?php echo $this->baseUrl(); ?>/admin/contato/index">
                                    <strong>Ver todos os Contatos</strong>
                                    <i class="icon-angle-right"></i>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <!--END MESSAGES SECTION -->
                <?php endif; ?>

                <!--ADMIN SETTINGS SECTIONS -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="icon-user "></i>&nbsp; <i class="icon-chevron-down "></i>
                    </a>
                    <?php if($isMobile): ?>
                        <ul class="dropdown-menu dropdown-user" style="right: -277% !important;">
                    <?php else: ?>
                        <ul class="dropdown-menu dropdown-user" style="right: -2% !important;">
                    <?php endif; ?>
                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/admin/usuario/edit/id/<?php echo $session_login->coSeqPaciente; ?>"><i class="icon-user"></i> Perfil </a>
                        </li>
                        <?php if($session_login->coTipoLogin==4) :?>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/contrato-gog/cancel/id/<?php echo $session_login->coSeqPaciente; ?>"><i class="icon-off"></i> Cancelar Contrato </a>
                            </li>
                        <?php endif; ?>
                        <?php if($session_login->coTipoLogin==1) :?>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/configuracao/index"><i class="icon-gear"></i> Configurações </a>
                            </li>
                        <?php endif; ?>
                        <li class="divider"></li>
                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/admin/login/logout">
                                <i class="icon-signout"></i> Sair
                                <i class="icon-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>
                <!--END ADMIN SETTINGS -->
            </ul>

        </nav>

    </div>
    <!-- END HEADER SECTION -->

    <!-- MENU SECTION -->
    <div id="left" >
        <div class="media user-media well-small">
            <br />
            <div class="media-body">
                <h5 class="media-heading"> <?php echo $session_login->nmPaciente; ?></h5>
            </div>
            <br />
        </div>
        <ul id="menu" class="collapse">
            <li class="panel <?php if($controlerName=="index"){echo 'active';}?>">
                <a href="<?php echo $this->baseUrl(); ?>/admin/index" >
                    <i class="icon-home"></i> Início
                </a>
            </li>
            <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3) :?>
                <li class="panel <?php if($controlerName=="usuario"){echo 'active';}?>">
                    <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#component-nav">
                        <i class="icon-user"> </i> Usuário
                        <span class="pull-right">
                          <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="component-nav">
                        <li class=""><a href="<?php echo $this->baseUrl(); ?>/admin/usuario/add"><i class="icon-angle-right"></i> Cadastrar </a></li>
                        <li class=""><a href="<?php echo $this->baseUrl(); ?>/admin/usuario"><i class="icon-angle-right"></i> Listar </a></li>
                        <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2) :?>
                            <li class=""><a href="<?php echo $this->baseUrl(); ?>/admin/usuario/funcionario"><i class="icon-angle-right"></i> Funcionários MarqSaúde </a></li>
                        <?php endif; ?>
                    </ul>
                </li>
            <?php endif; ?>
            <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3 || $session_login->coTipoLogin==6 || $session_login->coTipoLogin==7) :?>
                <li class="panel <?php if($controlerName=="cliente" || $controlerName=="dependente"){echo 'active';}?>">
                    <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle collapsed" data-target="#form-nav">
                        <i class="icon-male"></i> Cliente
                        <span class="pull-right">
                            <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="form-nav">
                        <li class="">
                            <a href="<?php echo $this->baseUrl(); ?>/admin/cliente/index"><i class="icon-angle-right"></i> Listar </a>
                        </li>
                        <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3 || $session_login->coTipoLogin==6) :?>
                            <li class=""><a href="<?php echo $this->baseUrl(); ?>/admin/cliente/add"><i class="icon-angle-right"></i> Cadastrar </a></li>
                        <?php endif; ?>
                        <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3) :?>
                            <li class="">
                                <a href="<?php echo $this->baseUrl(); ?>/admin/cliente/excluded"><i class="icon-angle-right"></i> Excluidos </a>
                            </li>
                        <?php endif; ?>
                        <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3 || $session_login->coTipoLogin==6) :?>
                            <a href="javascript:void(0)" data-parent="#DDL-nav" data-toggle="collapse" class="accordion-toggle" data-target="#dependente">
                                <i class="icon-sitemap"></i>&nbsp; Dependentes
                                <span class="pull-right" style="margin-right: 20px;">
                                    <i class="icon-angle-left"></i>
                                </span>
                            </a>
                            <ul class="collapse" id="dependente">
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/dependente/cliente"><i class="icon-angle-right"></i> Listar Cliente </a>
                                </li>
                            </ul>
                        <?php endif; ?>
                    </ul>
                </li>
            <?php endif; ?>
            <?php if($session_login->coTipoLogin==4) :?>
                <?php if($this->dataClienteDependentes[0]["nu_dependentes"] != 0){ ?>
                    <li class="panel <?php if($controlerName=="dependente"){echo 'active';}?>">
                        <a href="javascript:void(0)" data-parent="#DDL-nav" data-toggle="collapse" class="accordion-toggle" data-target="#dependente">
                            <i class="icon-sitemap"></i>&nbsp; Dependentes
                                        <span class="pull-right">
                                            <i class="icon-angle-left"></i>
                                        </span>
                        </a>
                        <ul class="collapse" id="dependente">
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/dependente/index"><i class="icon-angle-right"></i> Listar </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/dependente/add"><i class="icon-angle-right"></i> Cadastrar </a>
                            </li>
                        </ul>
                    </li>
                <?php } ?>
            <?php endif; ?>
            <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2) :?>
                <li class="panel <?php if($controlerName=="caixa"){echo 'active';}?>">
                    <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#pagesr-nav">
                        <i class="icon-archive"></i> Caixa
                        <span class="pull-right">
                            <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="pagesr-nav">
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/caixa/index"><i class="icon-angle-right"></i> Listar </a></li>
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/caixa/add"><i class="icon-angle-right"></i> Cadastrar </a></li>
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/caixa/extrato"><i class="icon-angle-right"></i> Extrato </a></li>
                    </ul>
                </li>
            <?php endif; ?>
            <li class="panel <?php if($controlerName=="procedimento" || $controlerName=="exame" || $controlerName=="consulta" || $controlerName=="laboratorio"){echo 'active';}?>">
                <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#procedimento">
                    <i class="icon-th-list"></i> Procedimento
                    <span class="pull-right">
                        <i class="icon-angle-left"></i>
                    </span>
                </a>
                <ul class="collapse" id="procedimento">
                    <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3) :?>
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/procedimento/index"><i class="icon-angle-right"></i> Listar Procedimentos </a></li>
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/procedimento/add"><i class="icon-angle-right"></i> Cadastrar Procedimentos </a></li>
                    <?php endif; ?>
                    <a href="javascript:void(0)" data-parent="#DDL-nav" data-toggle="collapse" class="accordion-toggle" data-target="#exame">
                        <i class="icon-heart"></i>&nbsp; Exames
                        <span class="pull-right" style="margin-right: 20px;">
                            <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="exame">
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/exame/index"><i class="icon-angle-right"></i> Listar </a></li>
                        <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3) :?>
                            <li><a href="<?php echo $this->baseUrl(); ?>/admin/exame/add"><i class="icon-angle-right"></i> Cadastrar </a></li>
                        <?php endif; ?>
                    </ul>
                    <a href="javascript:void(0)" data-parent="#DDL-nav" data-toggle="collapse" class="accordion-toggle" data-target="#laboratorio">
                        <i class="icon-medkit"></i>&nbsp; Laboratório
                        <span class="pull-right" style="margin-right: 20px;">
                            <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="laboratorio">
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/laboratorio/index"><i class="icon-angle-right"></i> Listar </a></li>
                        <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3) :?>
                            <li><a href="<?php echo $this->baseUrl(); ?>/admin/laboratorio/add"><i class="icon-angle-right"></i> Cadastrar </a></li>
                        <?php endif; ?>
                    </ul>
                    <a href="javascript:void(0)" data-parent="#DDL-nav" data-toggle="collapse" class="accordion-toggle" data-target="#consulta">
                        <i class="icon-stethoscope"></i>&nbsp; Consulta
                        <span class="pull-right" style="margin-right: 20px;">
                            <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="consulta">
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/consulta/index"><i class="icon-angle-right"></i> Listar </a></li>
                        <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3) :?>
                            <li><a href="<?php echo $this->baseUrl(); ?>/admin/consulta/add"><i class="icon-angle-right"></i> Cadastrar </a></li>
                        <?php endif; ?>
                    </ul>
                </ul>
            </li>
            <li class="panel <?php if($controlerName=="corpo-clinico"){echo 'active';}?>">
                <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#corpo-clinico">
                    <i class="icon-user-md"></i> Corpo Clínico
                    <span class="pull-right">
                        <i class="icon-angle-left"></i>
                    </span>
                </a>
                <ul class="collapse" id="corpo-clinico">
                    <li><a href="<?php echo $this->baseUrl(); ?>/admin/corpo-clinico/index"><i class="icon-angle-right"></i> Listar </a></li>
                    <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3) :?>
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/corpo-clinico/add"><i class="icon-angle-right"></i> Cadastrar </a></li>
                    <?php endif; ?>
                </ul>
            </li>
            <li class="panel <?php if($controlerName=="prestador"){echo 'active';}?>">
                <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#prestador">
                    <i class="icon-link"></i> Prestador
                    <span class="pull-right">
                        <i class="icon-angle-left"></i>
                    </span>
                </a>
                <ul class="collapse" id="prestador">
                    <li><a href="<?php echo $this->baseUrl(); ?>/admin/prestador/index"><i class="icon-angle-right"></i> Listar </a></li>
                    <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2) :?>
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/prestador/add"><i class="icon-angle-right"></i> Cadastrar </a></li>
                    <?php endif; ?>
                </ul>
            </li>
            <?php if($session_login->coTipoLogin==1) :?>
                <li class="panel <?php if($controlerName=="contrato-gog"){echo 'active';}?>">
                    <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#contrato-gog">
                        <i class="icon-file-alt"></i> Contratos
                        <span class="pull-right">
                            <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="contrato-gog">
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/contrato-gog/index"><i class="icon-angle-right"></i> Listar </a></li>
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/contrato-gog/add"><i class="icon-angle-right"></i> Cadastrar </a></li>
                    </ul>
                </li>
            <?php endif; ?>
            <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2) :?>
                <li class="panel <?php if($controlerName=="mais-voce"){echo 'active';}?>">
                    <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#mais-voce">
                        <i class="icon-hand-right "></i> Mais Você
                        <span class="pull-right">
                            <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="mais-voce">
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/mais-voce/index"><i class="icon-angle-right"></i> Listar </a></li>
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/mais-voce/add"><i class="icon-angle-right"></i> Cadastrar </a></li>
                    </ul>
                </li>
            <?php endif; ?>
            <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3) :?>
                <!--li class="panel <?php if($controlerName=="servicos"){echo 'active';}?>">
                    <a href="#" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#servicos">
                        <i class="icon-coffee"></i> Serviços
                        <span class="pull-right">
                            <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="servicos">
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/servicos/index"><i class="icon-angle-right"></i> Listar </a></li>
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/servicos/add"><i class="icon-angle-right"></i> Cadastrar </a></li>
                    </ul>
                </li-->
            <?php endif; ?>
            <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2) :?>
                <li class="panel <?php if($controlerName=="sobre"){echo 'active';}?>">
                    <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#sobre">
                        <i class="icon-text-width"></i> Sobre
                        <span class="pull-right">
                            <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="sobre">
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/sobre/edit"><i class="icon-angle-right"></i> Editar </a></li>
                    </ul>
                </li>
            <?php endif; ?>
            <?php if($session_login->coTipoLogin==4) :?>
                <li class="panel <?php if($controlerName=="cartao"){echo 'active';}?>">
                    <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#cartao">
                        <i class="icon-credit-card"></i> Cartão
                        <span class="pull-right">
                            <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="cartao">
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/cartao/view"><i class="icon-angle-right"></i> Virtual </a></li>
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/cartao/print" target="_blank"><i class="icon-angle-right"></i> Imprimir </a></li>
                    </ul>
                </li>
            <?php endif; ?>
            <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3 || $session_login->coTipoLogin==4 || $session_login->coTipoLogin==6) :?>
                <li class="panel <?php if($controlerName=="valores"){echo 'active';}?>">
                    <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#valores">
                        <i class="icon-usd"></i> Valores
                            <span class="pull-right">
                                <i class="icon-angle-left"></i>
                            </span>
                    </a>
                    <ul class="collapse" id="valores">
                        <a href="<?php echo $this->baseUrl(); ?>/admin/valores/exame" data-parent="#DDL-nav" data-toggle="collapse" class="accordion-toggle" data-target="#exame_valor">
                            <i class="icon-heart"></i>&nbsp; Exames Diagnosticos
                        </a>
                        <a href="<?php echo $this->baseUrl(); ?>/admin/valores/laboratorio" data-parent="#DDL-nav" data-toggle="collapse" class="accordion-toggle" data-target="#laboratorio_valor">
                            <i class="icon-medkit"></i>&nbsp; Exames Laboratoriais
                        </a>
                        <a href="<?php echo $this->baseUrl(); ?>/admin/valores/consulta" data-parent="#DDL-nav" data-toggle="collapse" class="accordion-toggle" data-target="#consulta_valor">
                            <i class="icon-stethoscope"></i>&nbsp; Consulta
                        </a>
                    </ul>
                </li>
            <?php endif; ?>
            <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2) :?>
                <li class="panel <?php if($controlerName=="perguntas"){echo 'active';}?>">
                    <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#perguntas">
                        <i class="icon-tasks"></i> Perguntas
                        <span class="pull-right">
                            <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="perguntas">
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/perguntas/index"><i class="icon-angle-right"></i> Listar </a></li>
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/perguntas/add"><i class="icon-angle-right"></i> Cadastrar </a></li>
                    </ul>
                </li>
            <?php endif; ?>
            <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2) :?>
                <li class="panel <?php if($controlerName=="blog"){echo 'active';}?>">
                    <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#blog">
                        <i class="icon-comment"></i> Blog
                        <span class="pull-right">
                            <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="blog">
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/blog/index"><i class="icon-angle-right"></i> Listar </a></li>
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/blog/add"><i class="icon-angle-right"></i> Cadastrar </a></li>
                    </ul>
                </li>
            <?php endif; ?>
            <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3) :?>
                <li class="panel <?php if($controlerName=="cancelamento"){echo 'active';}?>">
                    <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#cancelamento">
                        <i class="icon-ban-circle"></i> Cancelamento
                        <span class="pull-right">
                            <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="cancelamento">
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/cancelamento/cliente"><i class="icon-angle-right"></i> Cliente </a></li>
                    </ul>
                </li>
            <?php endif; ?>
            <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3) :?>
                <li class="panel <?php if($controlerName=="contato"){echo 'active';}?>">
                    <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#contato">
                        <i class="icon-envelope-alt"></i> Contatos
                        <span class="pull-right">
                            <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="contato">
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/contato/index"><i class="icon-angle-right"></i> Listar </a></li>
                    </ul>
                </li>
            <?php endif; ?>
            <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3) :?>
                <li class="panel <?php if($controlerName=="simulacao"){echo 'active';}?>">
                    <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#orcamento">
                        <i class="icon-reorder"></i> Simulação
                        <span class="pull-right">
                            <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="orcamento">
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin/simulacao/index"><i class="icon-angle-right"></i> Listar </a></li>
                    </ul>
                </li>
            <?php endif; ?>
            <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2 || $session_login->coTipoLogin==3) :?>
                <li class="panel <?php if($controlerName=="relatorio"){echo 'active';}?>">
                    <a href="javascript:void(0)" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#relatorio">
                        <i class="icon-folder-open"> </i> Relatório
                        <span class="pull-right">
                          <i class="icon-angle-left"></i>
                        </span>
                    </a>
                    <ul class="collapse" id="relatorio">
                        <li class=""><a href="<?php echo $this->baseUrl(); ?>/admin/relatorio/pagamento"><i class="icon-angle-right"></i> Pagamento </a></li>
                    </ul>
                </li>
            <?php endif; ?>

        </ul>
    </div>
    <!--END MENU SECTION -->

    <!--PAGE CONTENT -->
    <div id="content">
        <div class="inner" style="min-height: 762px;">
            <div class="row">&nbsp;</div>
            <div class="row">&nbsp;</div>
            <div class="row">
                <div class="col-lg-1"></div>
                <div class="col-lg-10">
                    <form action="javascript:void(0)" onSubmit="return buscaGeral(this);" method="post" id="form-busca" role="form">
                        <div class="form-group input-group">
                            <input name="searchword" onkeyup="searchText(this);" class="form-control input-block-level mod-search-searchword" id="tags" type="text" placeholder="O que quer buscar?">
                            <input type="hidden" name="task" value="search" />
                            <input type="hidden" name="option" value="com_search" />
                            <input type="hidden" name="Itemid" value="0" />
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="icon-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                </div>
                <div class="col-lg-1"></div>
            </div>
            <hr />
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
    <!--END PAGE CONTENT -->

    <!-- RIGHT STRIP  SECTION -->
    <div id="right" style="height: 591px;">
        <div class="well well-small">
            <ul class="list-unstyled">
                <li>
                    <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2) :?>
                        <?php echo $this->dataCaixaE["nm_caixa"]; ?>:
                    <?php endif; ?>
                    <?php if($session_login->coTipoLogin==3 || $session_login->coTipoLogin==5) :?>
                        Clientes Cadastrados:
                    <?php endif; ?>
                </li>
                <li>
                    <?php if($session_login->coTipoLogin==1 || $session_login->coTipoLogin==2) :?>
                        R$ <span><?php echo number_format($this->dataCaixaE["nu_saldo"], 2, ',', '.'); ?></span>
                    <?php endif; ?>
                    <?php if($session_login->coTipoLogin==3 | $session_login->coTipoLogin==5) :?>
                        Quantidade: <span><?php echo $this->dataCaixaE["q"]; ?></span>
                    <?php endif; ?>
                </li>
            </ul>
        </div>
    </div>
    <!-- END RIGHT STRIP  SECTION -->
</div>
<!--END MAIN WRAPPER -->

<!-- FOOTER -->
<div id="footer">
    <p>&copy;  MarqSaúde <span>Vantagens</span> &nbsp;<i>2017</i> &nbsp;</p>
</div>
<!--END FOOTER -->
<script src="<?php echo $this->baseUrl(); ?>/adm/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/adm/plugins/modernizr-custom.js"></script>
<!--script src="<?php echo $this->baseUrl(); ?>/adm/plugins/modernizr-2.6.2-respond-1.1.0.min.js"></script-->

<!--script src="<?php echo $this->baseUrl(); ?>/adm/plugins/flot/jquery.flot.js"></script-->
<!--script src="<?php echo $this->baseUrl(); ?>/adm/plugins/flot/jquery.flot.resize.js"></script-->
<!--script src="<?php echo $this->baseUrl(); ?>/adm/plugins/flot/jquery.flot.time.js"></script-->
<!--script  src="<?php echo $this->baseUrl(); ?>/adm/plugins/flot/jquery.flot.stack.js"></script-->
<script src="<?php echo $this->baseUrl(); ?>/adm/js/for_index.js"></script>

</body>

<!-- END BODY -->
</html>








