<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <style>
        .text-blog{
            background-color: #FFFFFF;
        }
    </style>
</head>

<!-- END HEAD -->

<!-- BEGIN BODY -->
<body>
<?php echo $this->layout()->content; ?>
</body>
</html>