<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login - MARQ Saúde</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="description" content="Signature Pad - HTML5 canvas based smooth signature drawing using variable width spline interpolation.">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <link rel="icon" href="<?php echo $this->baseUrl(); ?>/site/images/favicon.ico">
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/jquery.corner.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/jquery.validate.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/css_browser_selector.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/js.js"></script>

    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/data/css/layout/style.default.css" type="text/css" id="style_default" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/gogs/css/style.css" type="text/css" id="style" />
    <style>
        @font-face {
            font-family: "Vipnagorgialla";
            src: url("<?php echo $this->baseUrl(); ?>/site/fonts/marq_saude/vipnagorgialla.regular.ttf");
        }
        @font-face {
            font-family: "SignPainter";
            src: url("<?php echo $this->baseUrl(); ?>/site/fonts/marq_saude/signpainter.otf");
        }
        @font-face {
            font-family: 'DJBDearStNick';
            src: url('<?php echo $this->baseUrl(); ?>/gogs/fonts/DJBDearStNick.ttf');
            font-weight: normal;
            font-style: normal;
        }
        @font-face {
            font-family: 'Museo900';
            src: url('<?php echo $this->baseUrl(); ?>/gogs/fonts/Museo900-Regular.otf');
            font-weight: normal;
            font-style: normal;
        }
        .logopanel{
            font-family: DJBDearStNick;
            font-size: 61px;
        }
    </style>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <![endif]-->
</head>


<body class="signin" style="background: #85ccd9;">
<div style="display: none">
    <div id="url-page"><?php echo $this->baseUrl(); ?></div>
</div>
<!-- Preloader -->
<div id="preloader">
    <div id="status"><i class="fa fa-spinner fa-spin"></i></div>
</div>

<div id="valida" style="display: none;">1</div>

<section style="background: #f7f7f7;">

    <div class="signinpanel">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="logopanel" style="height: 112px;">
                    <img src="<?php echo $this->baseUrl(); ?>/def/imagens/logo_admin.png">
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
        <div class="row">

            <!--div class="col-md-7">

                <div class="signin-info">
                    <div class="logopanel">

                    </div>
                </div>

            </div--><!-- col-sm-7 -->
            <div class="col-md-3"></div>
            <div class="col-md-6" style="background: #f7f7f7;">
                <form action="javascript:void(0);" method="post" onSubmit="return validLogin(this);">
                    <div id="erroMessage"></div>
                    <input type="text" name="usuarioLogin" class="form-control uname" placeholder="Usuário">
                    <input  type="password" name="senhaLogin" class="form-control pword"  placeholder="Senha">
                    <button type="submit" class="btn btn-success-gog btn-block">Entrar</button>
                </form>
            </div><!-- col-sm-5 -->
            <div class="col-md-3"></div>

        </div><!-- row -->



    </div><!-- signin -->

</section>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/libarys/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/libarys/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/libarys/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/libarys/modernizr.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/libarys/retina.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/libarys/custom.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/global.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/gogs/js/login/index.js"></script>
</body>
</html>