<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login - MARQ Saúde</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="<?php echo $this->baseUrl(); ?>/site/images/q_do_qsaude.ico">
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/jquery.corner.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/jquery.validate.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/css_browser_selector.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/js.js"></script>
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/data/css/layout/style.default.css" type="text/css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/site/style.css" type="text/css" />

    <style>
        @font-face{
            font-family:"MarckScript";
            src:url('<?php echo $this->baseUrl(); ?>/site/font/marckscript-regular.ttf');
        }
        @font-face{
            font-family:"CenturyGothic";
            src:url('<?php echo $this->baseUrl(); ?>/site/font/CenturyGothicRegular.ttf');
        }
        @font-face{
            font-family:"KGAlwaysAGoodTime";
            src:url('<?php echo $this->baseUrl(); ?>/site/font/KGAlwaysAGoodTime.ttf');
        }
        @font-face{
            font-family:"ERASB";
            src:url('<?php echo $this->baseUrl(); ?>/site/font/ERASB.ttf');
        }
    </style>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <![endif]-->
</head>


<body class="signin" style="background: rgba(108, 195, 196, 0.7);">
<div style="display: none">
    <div id="url-page"><?php echo $this->baseUrl(); ?></div>
</div>
<!-- Preloader -->
<div id="preloader">
    <div id="status"><i class="fa fa-spinner fa-spin"></i></div>
</div>

<div id="valida" style="display: none;">1</div>

<section style="background: #ffffff;">

    <div class="signinpanel">
        <div class="row">

            <div class="col-md-12">
                <a href="<?php echo $this->baseUrl(); ?>/">
                    <div class="logopanel">

                        <img src="<?php echo $this->baseUrl(); ?>/def/images/logo_admin.png" id="qsaude" width="377">

                    </div>
                </a>
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">&nbsp;</div>
        </div>
        <div class="row">

            <!--div class="col-md-7">

                <div class="signin-info">
                    <div class="logopanel">

                    </div>
                </div>

            </div--><!-- col-sm-7 -->
            <div class="col-md-3"></div>
            <div class="col-md-6" style="background: #ffffff;">
                <form action="<?php echo $this->baseUrl();?>/admin/login/logar" method="Post" onSubmit="return validLogin(this);">
                    <div id="erroMessage"></div>
                    <input type="text" name="usuarioLogin" class="form-control uname" placeholder="Usuário">
                    <input  type="password" name="senhaLogin" class="form-control pword"  placeholder="Senha">
                    <button type="submit" class="btn btn-logar btn-block">Entrar</button>
                </form>
            </div><!-- col-sm-5 -->
            <div class="col-md-3"></div>

        </div><!-- row -->



    </div><!-- signin -->

</section>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/libarys/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/libarys/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/libarys/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/libarys/modernizr.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/libarys/retina.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/js/libarys/custom.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/global.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/data/jsView/login/index.js"></script>
</body>
</html>