<?php

$controller = Zend_Controller_Front::getInstance();
$controlerName = $controller->getRequest()->getControllerName();
$actionName = $controller->getRequest()->getActionName();
$read = Zend_Auth::getInstance()->getStorage()->read();

$session_login = new Zend_Session_Namespace('Login');
$actual_link = 'http://'.$_SERVER['HTTP_HOST'];

?>


<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Saúde pra você</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
        @font-face {
            font-family: "Vipnagorgialla";
            src: url("<?php echo $this->baseUrl(); ?>/site/font/marq_saude/vipnagorgialla.regular.ttf");
        }
        @font-face {
            font-family: "SignPainter";
            src: url("<?php echo $this->baseUrl(); ?>/site/font/marq_saude/signpainter.otf");
        }
        @font-face{
            font-family:"Tobago";
            src:url('<?php echo $this->baseUrl(); ?>/site/font/OPTITamil-BlackAgency.otf');
        }
        @font-face{
            font-family:"MarckScript";
            src:url('<?php echo $this->baseUrl(); ?>/site/font/marckscript-regular.ttf');
        }
        @font-face{
            font-family:"CenturyGothic";
            src:url('<?php echo $this->baseUrl(); ?>/site/font/CenturyGothicRegular.ttf');
        }
        @font-face{
            font-family:"KGAlwaysAGoodTime";
            src:url('<?php echo $this->baseUrl(); ?>/site/font/KGAlwaysAGoodTime.ttf');
        }
        @font-face{
            font-family:"ERASB";
            src:url('<?php echo $this->baseUrl(); ?>/site/font/ERASB.ttf');
        }
        @font-face{
            font-family:"NexaLight";
            src:url('<?php echo $this->baseUrl(); ?>/site/font/NexaLight.otf');
        }
        ul.wysihtml5-toolbar > li {
            position: relative;
        }
    </style>

    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/site/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/site/css/bootstrap-responsive.min.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/site/css/font-awesome.min.css">
    <?php if(isset($session_login->logado) && $session_login->logado==true) :?>
        <?php if($session_login->coTipoLogin==1): ?>
            <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/site/css/main_new.css">
        <?php else: ?>
            <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/site/css/main.css">
        <?php endif; ?>
    <?php else: ?>
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/site/css/main.css">
    <?php endif; ?>
    <?php //if($this->isMobile) :?>
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/site/css/w3.css">
    <?php //endif; ?>
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/site/css/sl-slide.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/site/css/prettyPhoto.css">
    <?php if($session_login->coTipoLogin==1): ?>
        <link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/site/images/cruz_vantagens.ico">
    <?php else: ?>
        <link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/site/images/q_do_qsaude.ico">
    <?php endif; ?>

    <script src="<?php echo $this->baseUrl(); ?>/site/js/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/site/js/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/site/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/site/js/jquery-ui.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/site/js/jquery.ui.totop.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/site/js/jquery.mask.min.js"></script>
    <!-- /Required javascript files for Slider -->
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/global.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/site/js/main.js"></script>
    <!-- Required javascript files for Slider -->
    <script src="<?php echo $this->baseUrl(); ?>/site/js/jquery.ba-cond.min.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/site/js/jquery.slitslider.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/site/js/jquery.prettyPhoto.js"></script>

    <!-- Le fav and touch icons -->
    <!--link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png"-->
</head>

<body>

<div style="display: none" id="url-page"><?php echo $this->baseUrl(); ?></div>

<?php if($this->isMobile) :?>
    <div id="id01" class="w3-modal">
        <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">

            <div class="w3-center"><br>
                <span onclick="document.getElementById('id01').style.display='none'" class="w3-button w3-xlarge w3-hover-red w3-display-topright" title="Close Modal">&times;</span>
                <span class="w3-circle w3-margin-top mais-vantagens" style="width:30%">+ Vantagens</span>
            </div>

            <div id="loginForm">
                <form class="form-inline w3-container" method="post" id="form-login" onSubmit="return login(this);">
                    <div class="w3-section">
                        <label><b>Login (Email)</b></label>
                        <input class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Entre com o Login" name="user" required>
                        <label><b>Senha</b></label>
                        <input class="w3-input w3-border" type="password" placeholder="Entre com a Senha" name="passwd" required>
                        <button class="w3-button w3-block w3-green w3-section w3-padding" type="submit">Login</button>
                    </div>
                </form>

                <div class="w3-container w3-border-top w3-padding-16 w3-light-grey">
                    <a href="javascript:void(0);" onclick="esquecerSenha();" class="w3-button w3-red">Esqueceu a senha?</a>
                    <span class="w3-right w3-padding w3-hide-small">Forgot <a href="#">password?</a></span>
                </div>
            </div>

        </div>
    </div>
<?php endif; ?>
<!--Header-->
<?php if($this->isMobile) :?>
    <header class="navbar navbar-fixed-top navbar-inner-mobile">
<?php else :?>
    <header class="navbar navbar-fixed-top">
<?php endif; ?>
    <?php if($this->isMobile) :?>
        <div class="navbar-inner navbar-inner-mobile">
    <?php else :?>
        <div class="navbar-inner">
    <?php endif; ?>
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a href="<?php echo $this->baseUrl(); ?>/">
                <?php if(isset($session_login->logado) && $session_login->logado==true) :?>
                    <?php if($session_login->coTipoLogin==1): ?>
                        <div id="logo-new" class="pull-left"></div>
                    <?php else: ?>
                        <div id="logo" class="pull-left"></div>
                    <?php endif; ?>
                <?php else: ?>
                    <div id="logo" class="pull-left"></div>
                <?php endif; ?>
                <?php if($session_login->coTipoLogin!=1): ?>
                    <span id="saude">saúde</span>
                    <?php if($this->isMobile) :?>
                        <span id="vantagens" style="margin-top: 5.4%; margin-bottom: 1%;">+ Vantagens</span>
                    <?php else :?>
                        <span id="vantagens">+ Vantagens</span>
                    <?php endif; ?>
                <?php endif; ?>
            </a>
            <div class="nav-collapse collapse pull-right">
                <ul class="nav">
                    <li class="<?php if($controlerName=="index") :?>active<?php  endif; ?>"><a href="<?php echo $this->baseUrl(); ?>/">Início</a></li>
                    <?php if(!$session_login->logado): ?>
                        <li class="<?php if($controlerName=="cliente") :?>active<?php  endif; ?>"><a href="<?php echo $this->baseUrl(); ?>/cliente/">Cadastro</a></li>
                    <?php endif; ?>
                    <li class="<?php if($controlerName=="galeria") :?>active<?php  endif; ?>"><a href="<?php echo $this->baseUrl(); ?>/galeria/">Galeria</a></li>
                    <li class="<?php if($controlerName=="perguntas") :?>active<?php  endif; ?>"><a href="<?php echo $this->baseUrl(); ?>/perguntas/">Perguntas</a></li>
                    <li class="<?php if($controlerName=="contato") :?>active<?php  endif; ?>"><a href="<?php echo $this->baseUrl(); ?>/contato/">Contato</a></li>
                    <li class="dropdown <?php if($controlerName=="sobre" || $controlerName=="por-dentro" || $controlerName=="prestador" || $controlerName=="mais-vantagens") :?>active<?php  endif; ?>">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sobre <i class="icon-angle-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->baseUrl(); ?>/sobre/">Sobre</a></li>
                            <li><a href="<?php echo $this->baseUrl(); ?>/sobre/missao-visao-valores">Missão, Visão e Valores</a></li>
                            <li><a href="<?php echo $this->baseUrl(); ?>/por-dentro/">Fique por dentro!</a></li>
                            <li><a href="<?php echo $this->baseUrl(); ?>/prestador/">Parceiros</a></li>
                            <li><a href="<?php echo $this->baseUrl(); ?>/mais-vantagens/">+ Vantagens</a></li>
                        </ul>
                    </li>
                    <?php if(isset($session_login->logado) && $session_login->logado==true) {?>
                        <li class="login" id="in-paciente">
                            <a data-toggle="modal" href="<?php echo $this->baseUrl(); ?>/admin/"><i class="icon-user"></i></a>
                        </li>
                        <li id="nm-paciente">
                            <a href="<?php echo $this->baseUrl(); ?>/admin/" style="margin-top: 2px; margin-left: -17px; float: left; font-size: 12px; color: #34495e; text-transform: unset;">
                                <span>
                                    <?php echo $session_login->nmPaciente; ?>
                                </span>
                            </a>
                        </li>
                    <?php }else { ?>
                        <?php if($this->isMobile) :?>
                            <li class="login">
                                <button onclick="document.getElementById('id01').style.display='block'" class="w3-button w3-green w3-large">Login</button>
                            </li>
                        <?php else : ?>
                            <li class="login">
                                <a data-toggle="modal" href="#loginForm" style="text-transform: none;"><i class="icon-lock"></i>&nbsp; Login</a>
                            </li>
                        <?php endif; ?>
                    <?php } ?>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</header>
<!-- /header -->

<?php echo $this->layout()->content; ?>

<!--Bottom-->
<section id="bottom" class="main">
    <!--Container-->
    <?php if($this->isMobile) :?>
        <div class="container" style="padding-right: 7%; padding-left: 7%;">
    <?php else : ?>
        <div class="container">
    <?php endif; ?>

        <!--row-fluids-->
        <div class="row-fluid">

            <!--Contact Form-->
            <div class="span3">
                <h4>ENDEREÇO</h4>
                <ul class="unstyled address">
                    <li>
                        <i class="icon-home"></i><strong>Endereço:</strong> QS 03, LOTE 03,05,07, <br/>
                        sobreloja 113 - Ed. Patio Capital - Águas Claras, Brasília - DF. <br/>
                    </li>
                    <li>
                        <i class="icon-map-marker"></i><strong>Cep:</strong> 71953-000
                    </li>
                    <li>
                        <i class="icon-building"></i><strong>Ponto de referência:</strong> Ao lado da Feibox e Taguatinga Shopping – Pistão Sul
                    </li>
                    <li>
                        <i class="icon-envelope"></i>
                        <strong>Email: </strong> qsaudevantagens@gmail.com
                    </li>
                    <li>
                        <i class="icon-globe"></i>
                        <strong>Website:</strong> www.qsaudevantagens.com.br
                    </li>
                    <li>
                        <i class="icon-phone"></i>
                        <strong>Telefone:</strong> (61) 2026-1313
                    </li>
                    <li>
                        <i class="icon-phone"></i>
                        <strong>WhatsApp:</strong> (61) 99668-1445
                    </li>
                </ul>
            </div>
            <!--End Contact Form-->

            <!--Important Links-->
            <div class="span5">
                <div class="span3"></div>
                <div class="span8">
                    <div style="margin-top: 67px;">
                        <?php if(isset($session_login->logado) && $session_login->logado==true) :?>
                            <?php if($session_login->coTipoLogin==1): ?>
                                <div id="logo_vantagens"></div>
                                <div class="span11">
                                    <span style="margin-top: 7px; float: left; text-align: center; font-size: 17px; margin-left: 10px;">Não é um plano de saúde.</span>
                                </div>
                            <?php else: ?>
                                <span style="color: #f0ad4e; font-family: 'ERASB'; font-size: 63px; margin-top: 3px; float: left; margin-bottom: 7px;">Q</span>
                                <span style="color: #d0d0d0; font-family: 'ERASB'; font-size: 41px; margin-top: 7px; margin-left: 7px; float: left;">saúde</span>
                                <span style="color: #d0d0d0; font-family: 'KGAlwaysAGoodTime'; font-size: 17px; margin-top: 14px; float: left; margin-left: 7px;">+ Vantagens</span><br/>
                                <div class="span1"></div>
                                <div class="span11">
                                    <span style="margin-top: 7px; float: left; text-align: center; font-size: 17px;">Não é um plano de saúde.</span>
                                </div>
                                <!--div id="logo_vantagens_marq_saude"></div-->
                            <?php endif; ?>
                        <?php else: ?>
                            <span style="color: #f0ad4e; font-family: 'ERASB'; font-size: 63px; margin-top: 3px; float: left; margin-bottom: 7px;">Q</span>
                            <span style="color: #d0d0d0; font-family: 'ERASB'; font-size: 41px; margin-top: 7px; margin-left: 7px; float: left;">saúde</span>
                            <span style="color: #d0d0d0; font-family: 'KGAlwaysAGoodTime'; font-size: 17px; margin-top: 14px; float: left; margin-left: 7px;">+ Vantagens</span><br/>
                            <div class="span1"></div>
                            <div class="span11">
                                <span style="margin-top: 7px; float: left; text-align: center; font-size: 17px;">Não é um plano de saúde.</span>
                            </div>
                        <?php endif; ?>
                        <div class="span1"></div>
                    </div>
                </div>
                <div class="span1"></div>
            </div>
            <!--End Archives-->

            <div class="span4">
                <div class="row-fluid first">
                    <div class="span12">
                        <div class="newsletter_text">
                            Deixe seu email, para que possamos entrar em contato.
                        </div>
                        <div>
                            <form onsubmit="return validaNewsletter(this);" action="javascript:void(0);" method="post" class="newsletter-form" id="main-newsletter-form" name="newsletter-form">
                                <input type="text" name="nm_newsletter" maxlength="50" style="width: 64%;" placeholder="Email..." />
                                <button type="submit" class="btn btn-primary pull-right" style="width: 23%; height: 36px;">Enviar</button>
                            </form>
                        </div>
                    </div>
                    <div class="span12 fique-por-dentro">
                        <a href="<?php echo $this->baseUrl(); ?>/por-dentro/" ><i class="icon-comment icon-4x"></i> <span class="fique-por-dentro-link">Fique por dentro!</span></a>
                    </div>
                    <!--ul class="thumbnails">
                        <li class="span3"-->
                            <!--a href="http://www.flickr.com/photos/76029035@N02/6829540293/" title="01 (254) by Victor1558, on Flickr"><img src="http://farm8.staticflickr.com/7003/6829540293_bd99363818_s.jpg" width="75" height="75" alt="01 (254)"></a-->
                        <!--/li>
                        <li class="span3"-->
                            <!--a href="http://www.flickr.com/photos/76029035@N02/6829537417/" title="01 (196) by Victor1558, on Flickr"><img src="http://farm8.staticflickr.com/7013/6829537417_465d28e1db_s.jpg" width="75" height="75" alt="01 (196)"></a-->
                        <!--/li>
                        <li class="span3"-->
                            <!--a href="http://www.flickr.com/photos/76029035@N02/6829527437/" title="01 (65) by Victor1558, on Flickr"><img src="http://farm8.staticflickr.com/7021/6829527437_88364c7ec4_s.jpg" width="75" height="75" alt="01 (65)"></a-->
                        <!--/li>
                        <li class="span3"-->
                            <!--a href="http://www.flickr.com/photos/76029035@N02/6829524451/" title="01 (6) by Victor1558, on Flickr"><img src="http://farm8.staticflickr.com/7148/6829524451_a725793358_s.jpg" width="75" height="75" alt="01 (6)"></a-->
                        <!--/li>
                    </ul-->
                </div>
                <!--div class="row-fluid">
                    <ul class="thumbnails">
                        <li class="span3"-->
                            <!--a href="http://www.flickr.com/photos/76029035@N02/6829524451/" title="01 (6) by Victor1558, on Flickr"><img src="http://farm8.staticflickr.com/7148/6829524451_a725793358_s.jpg" width="75" height="75" alt="01 (6)"></a-->
                        <!--/li>
                        <li class="span3"-->
                            <!--a href="http://www.flickr.com/photos/76029035@N02/6829540293/" title="01 (254) by Victor1558, on Flickr"><img src="http://farm8.staticflickr.com/7003/6829540293_bd99363818_s.jpg" width="75" height="75" alt="01 (254)"></a-->
                        <!--/li>
                        <li class="span3"-->
                            <!--a href="http://www.flickr.com/photos/76029035@N02/6829537417/" title="01 (196) by Victor1558, on Flickr"><img src="http://farm8.staticflickr.com/7013/6829537417_465d28e1db_s.jpg" width="75" height="75" alt="01 (196)"></a-->
                        <!--/li>
                        <li class="span3"-->
                            <!--a href="http://www.flickr.com/photos/76029035@N02/6829527437/" title="01 (65) by Victor1558, on Flickr"><img src="http://farm8.staticflickr.com/7021/6829527437_88364c7ec4_s.jpg" width="75" height="75" alt="01 (65)"></a-->
                        <!--/li>
                    </ul>
                </div-->

            </div>

        </div>
    </div>
    <!--/container-->

</section>
<!--/bottom-->

<!--Footer-->
<footer id="footer">
    <div class="container">
        <div class="row-fluid">
            <?php if($this->isMobile) :?>
                <div class="span5 cp" style="padding-left: 7%; padding-right: 7%;">
            <?php else: ?>
                <div class="span5 cp">
            <?php endif; ?>
                &copy; 2017 Tony Anderson, Alessandra Xavier &amp; Felipe Braga <span>designer</span>
                <!--a href="javascript:void(0);" onclick="boleto();">rr</a-->
            </div>
            <!--/Copyright-->

            <div class="span6">
                <ul class="social pull-right">
                    <li><a href="#"><i class="icon-facebook"></i></a></li>
                    <li><a href="#"><i class="icon-twitter"></i></a></li>
                    <li><a href="#"><i class="icon-pinterest"></i></a></li>
                    <li><a href="#"><i class="icon-linkedin"></i></a></li>
                    <li><a href="#"><i class="icon-google-plus"></i></a></li>
                    <li><a href="#"><i class="icon-youtube"></i></a></li>
                    <li><a href="#"><i class="icon-tumblr"></i></a></li>
                    <li><a href="#"><i class="icon-dribbble"></i></a></li>
                    <li><a href="#"><i class="icon-rss"></i></a></li>
                    <li><a href="#"><i class="icon-github-alt"></i></a></li>
                    <li><a href="#"><i class="icon-instagram"></i></a></li>
                </ul>
            </div>

            <div class="span1">
                <a id="gototop" class="gototop pull-right" href="#"><i class="icon-angle-up"></i></a>
            </div>
            <!--/Goto Top-->
        </div>
    </div>
</footer>
<!--/Footer-->

<!--  Login form -->
<div class="modal hide fade in" id="loginForm" aria-hidden="false" style="height: 27%!important;">
    <div class="modal-header">
        <i class="icon-remove" data-dismiss="modal" aria-hidden="true"></i>
        <div class="text-esqueceu-senha">Logar com sua conta QSaúde</div>
    </div>
    <!--Modal Body-->
    <div class="modal-body">
        <form class="form-inline" method="post" id="form-login" onSubmit="return login(this);">
            <input type="text" class="input-small" placeholder="Email" name="user" required="required" style="width: 34%;" />
            <input type="password" class="input-small" placeholder="Senha" name="passwd" required="required" style="width: 34%;" />
            <button type="submit" class="btn btn-primary" style="padding: 10px 21px; margin-top: 2px;">Entrar</button>
        </form>
        <a href="javascript:void(0);" onclick="esquecerSenha();">Esqueceu a senha?</a>
    </div>
    <!--/Modal Body-->
</div>
<!--  /Login form -->

</body>
</html>