<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/site/css/register/date-picker.css" type="text/css"/>
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/adm/css/cliente/add.css" type="text/css"/>
<script type="text/javascript">
    var setContratoGog = <?php echo ($this->idContrato)?$this->idContrato:"false"; ?>;
</script>
<div id="loading"></div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Cadastrar Cliente
            </div>
            <div class="panel-body">
                <div class="">
                    <div class="col-sm-12">
                        <div style="text-align: center; color: #363636;">
                            <span style="margin-left: 8.7%;">&nbsp;</span>
                            <span class="icon-male icon-3x">&nbsp;</span>
                            <span style="margin-left: 8.7%;">&nbsp;</span>
                            <span class="icon-user icon-3x">&nbsp;</span>
                            <span style="margin-left: 8.7%;">&nbsp;</span>
                            <span class="icon-file icon-3x">&nbsp;</span>
                            <span style="margin-left: 8.7%;">&nbsp;</span>
                            <span class="icon-credit-card icon-3x">&nbsp;</span>
                            <span style="margin-left: 8.7%;">&nbsp;</span>
                        </div>
                    </div>
                </div>
                <div class="">
                    <div class="col-sm-12">
                        <div style="text-align: center; color: #363636;">
                            <span class="icon-circle">&nbsp;</span>
                            <span class="icon-circle">&nbsp;</span>
                            <span class="icon-circle">&nbsp;</span>
                            <span class="icon-circle">&nbsp;</span>
                            <span class="icon-circle">&nbsp;</span>
                            <span class="icon-circle">&nbsp;</span>
                            <span class="icon-circle">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                            <span class="icon-circle-blank">&nbsp;</span>
                        </div>
                    </div>
                </div>

                <div class="table-responsive" id="cartao-vantagem">
                    <form role="form" onSubmit="return validaVendedorCliente(this);" name="vendedorCliente" id="vendedorCliente">
                        <div id="dataTables-example_wrapper2" class="dataTables_wrapper form-inline" role="grid">
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <center>
                                        Selecione um Vendedor ou o sistema se o cadastro foi feita pela gerencia Q-Saúde.
                                    </center>
                                </div>
                                <div class="col-sm-12">&nbsp;</div>
                                <div class="col-sm-2">&nbsp;</div>
                                <div class="col-sm-8">
                                    <select class="form-control co_usuario" name="co_usuario">
                                        <option value="0">Selecione um Vendendor...</option>
                                        <?php foreach($this->dataUsuario as $value) :?>
                                             <option value="<?php echo $value["co_seq_usuario"]; ?>"><?php echo $value["nm_usuario"]; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="col-sm-2">&nbsp;</div>
                            </div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/cliente/index" class="btn btn-warning btn-lg btn-rect"><i class="icon-reply"></i>&nbsp;Clientes</a>
                                </div>
                                <div class="col-lg-6">
                                    <a href="javascript:void(0);" style="float: right;" class="btn btn-info btn-lg btn-rect" onclick="submitCadastroVendedorCliente();">Próximo&nbsp;<i class="icon-share-alt"></i></a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo $this->baseUrl(); ?>/adm/js/cliente/add.js"></script>