<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/def/css/scripts/prestador/index.css" />
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/def/js/scripts/prestador/index.js"></script>

<?php if(!Util_Util::isMobile()): ?>
    <section id="container-prestador" class="container">
<?php else: ?>
    <section id="container-prestador" class="container" style="width: 100%;">
<?php endif; ?>
    <!--div class="container" style="background-color: #ffffff;"-->
        <?php foreach($this->dataPrestador as $key=>$value) :?>
            <?php if(($key%3)==0):?>
                <div class="row-fluid">
            <?php endif; ?>
                    <div class="span4">
                        <center>
                            <div style="width: 77% !important;">
                                <!--i style="font-size: 48px" class="icon-bar-chart icon-large"></i-->
                                <?php list($width, $height, $type, $attr) = getimagesize(getcwd()."/site/images/prestador/".$value["lk_prestador"]); ?>
                                <?php $width = ($width>157)?157:$width; ?>
                                <a href="javascript:void(0);" onclick="abrirPrestador(<?php echo $value["co_seq_prestador"]; ?>)" title="<?php echo $value["nm_prestador"]; ?>"><img src="<?php echo $this->baseUrl()."/site/images/prestador/".$value["lk_prestador"] ?>" width="<?php echo $width; ?>"></a>
                                <p> </p>
                                <h4><?php echo $value["nm_prestador"]; ?></h4>
                                <?php if($this->session_login->logado && $this->session_login->coTipoLogin==1): ?>
                                    <p><?php echo Util_Util::getTextMinBlog($value["tx_sobre"]); ?></p>
                                <?php else: ?>
                                    <p><?php echo $value["tx_sobre"]; ?></p>
                                <?php endif; ?>
                            </div>
                        </center>
                    </div>
            <!--div class="span4">
                <div class="center">
                    <i style="font-size: 48px" class="icon-cog icon-large"></i>
                    <p> </p>
                    <h4>Web Design &amp; Development</h4>
                    <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio.</p>
                </div>
            </div>

            <div class="span4">
                <div class="center">
                    <i style="font-size: 48px" class="icon-heart icon-large"></i>
                    <p> </p>
                    <h4>Premium Wordpress Themes</h4>
                    <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio.</p>
                </div>
            </div-->
            <?php if((($key+1)%3)==0):?>
                </div>
                <br/><br/><br/>
            <?php endif; ?>
        <?php endforeach; ?>
        <!--div class="row-fluid">
            <div class="span4">
                <div class="center">
                    <i style="font-size: 48px" class="icon-globe icon-large"></i>
                    <p> </p>
                    <h4>Responsive Web Design</h4>
                    <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio.</p>
                </div>
            </div>

            <div class="span4">
                <div class="center">
                    <i style="font-size: 48px" class="icon-camera icon-large"></i>
                    <p> </p>
                    <h4>iOS Application Development</h4>
                    <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio.</p>
                </div>
            </div>

            <div class="span4">
                <div class="center">
                    <i style="font-size: 48px" class="icon-bullhorn icon-large"></i>
                    <p> </p>
                    <h4>Android Application Development</h4>
                    <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio.</p>
                </div>
            </div>

        </div>

        <hr-->

        <div class="center">

        </div>
        <p>&nbsp;</p>
    <!--/div-->
</section>