<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/site/css/MoneAdmin.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/site/css/Markdown.Editor.hack.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/site/css/jquery.cleditor-hack.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/site/css/bootstrap-wysihtml5-hack.css" />
<style>
    .wysihtml5-toolbar li{
        width: 197px;
        float: left;
        list-style-type: none;
    }
    .wysihtml5-toolbar li:nth-child(4){
        width: 157px;
        float: left;
        list-style-type: none;
    }
    .wysihtml5-toolbar li:nth-child(5){
        width: 37px;
        float: left;
        list-style-type: none;
    }
    .wysihtml5-toolbar li:nth-child(6){
        width: 37px;
        float: left;
        list-style-type: none;
    }
    .wysihtml5-toolbar li:nth-child(7){
        width: 37px;
        float: left;
        list-style-type: none;
    }
    .wysihtml5-toolbar .dropdown{
        width: 127px;
        float: left;
        list-style-type: none;
    }
    .wysihtml5-toolbar .dropdown:nth-child(1){
        margin-left: 27px;
    }
    .wysihtml5-toolbar .dropdown:nth-child(2){
        width: 72px;
        float: left;
        list-style-type: none;
        margin-bottom: 7px;
    }
    .wysihtml5-toolbar{
        text-align: center;
    }
</style>

<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/adm/js/sobre/edit.js"></script>


<!--PAGE CONTENT -->



    <div class="row">
        <div class="col-lg-12">


            <h2> Editar Sobre</h2>



        </div>
    </div>

    <hr />

    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <header>
                    <div class="icons"><i class="icon-th-large"></i></div>
                    <h5>Texto feito em HTML</h5>
                    <ul class="nav pull-right">
                        <li>
                            <div class="btn-group">
                                <a class="accordion-toggle btn btn-xs minimize-box" data-toggle="collapse"
                                   href="#div-1">
                                    <i class="icon-minus"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </header>
                <div id="div-1" class="body collapse in">
                    <form role="form" onSubmit="return validaEditarSobre(this);" name="editSobre" id="editSobre">
                        <textarea id="wysihtml5" class="form-control" rows="10" name="tx_sobre"><?php echo $this->dataSobre["tx_sobre"]; ?></textarea>
                        <input type="hidden" name="co_seq_sobre" value="<?php echo $this->dataSobre["co_seq_sobre"]; ?>"/>
                        <div class="form-actions">
                            <br />
                            <button onclick="submitEditarSobre();" class="btn btn-default" type="button" style="background-color: #5cb85c; color: #FFFFFF;">
                                Salvar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>



<script src="<?php echo $this->baseUrl(); ?>/site/js/modernizr-2.6.2-respond-1.1.0.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/site/js/wysihtml5-0.3.0.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/site/js/bootstrap-wysihtml5-hack.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/site/js/jquery.cleditor.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/site/js/Markdown.Converter.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/site/js/Markdown.Sanitizer.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/site/js/editorInit.js"></script>
<script>
    $(function () { formWysiwyg(); });
</script>