<div class="row">
    <div class="col-lg-12">
        <a href="javascript:void(0)" onclick="goBack();" class="btn btn-warning btn-flat btn-rect"><i class="icon-reply"></i>&nbsp;Voltar</a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">&nbsp;</div>
</div>

<div class="row">

    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="col-lg-12">
                    Laboratório <h4><?php echo $this->dataLaboratorio["nm_laboratorio"]; ?></h4>
                </div>
                <div class="col-lg-12">
                    <b>Valor c/ Cartão:</b> <?php echo "R$ ".number_format($this->dataLaboratorio["nu_valor"], 2, '.', ''); ?>
                </div>
                <div class="col-lg-12">&nbsp;</div>
            </div>
        </div>
    </div>

    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-4">&nbsp;</div>
            <div class="col-lg-4"><p style="text-align: center; font-size: 14px;">Prestadores</p></div>
            <div class="col-lg-4">&nbsp;</div>
        </div>
        <div class="row">
            <?php if(isset($this->dataProcedimentoPrestador[0])) :?>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Nome</th>
                                <th>Ação</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $i=1; ?>
                            <?php foreach($this->dataProcedimentoPrestador as $value): ?>
                                <tr>
                                    <td width="10%"><?php echo $i; ?></td>
                                    <td width="80%"><?php echo $value["nm_prestador"]; ?></td>
                                    <td width="10%">
                                        <a href="<?php echo $this->baseUrl(); ?>/admin/prestador/view/id/<?php echo $value["co_seq_prestador"]; ?>"><i class="icon-eye-open" title="Visualizar"></i></a>&nbsp;&nbsp;
                                    </td>
                                </tr>
                                <?php $i++; ?>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            <?php else :?>
                <div class="col-lg-6">
                    <p></p>
                    <h4>Não tem prestador vinculado...</h4>
                </div>
            <?php endif; ?>
        </div>
        <div class="col-lg-12">&nbsp;</div>
        <div class="col-lg-12">&nbsp;</div>
    </div>

</div>