<div class="panel panel-default">
    <div class="panel-heading">
        Lista de Perguntas
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Perguntas</th>
                    <th>Ação</th>
                </tr>
                </thead>
                <tbody>
                <?php $i=1; ?>
                <?php foreach($this->dataPerguntas as $value): ?>
                    <tr>
                        <td width="5%"><?php echo $i; ?></td>
                        <td width="82%"><?php echo $value["tx_pergunta"]; ?></td>
                        <td width="13%">
                            <a href="<?php echo $this->baseUrl(); ?>/admin/perguntas/view/id/<?php echo $value["co_seq_perguntas"]; ?>"><i class="icon-eye-open" title="Visualizar"></i></a>&nbsp;&nbsp;
                            <?php if($this->coTipoLogin==1 || $this->coTipoLogin==2) :?>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/perguntas/edit/id/<?php echo $value["co_seq_perguntas"]; ?>"><i class="icon-edit" title="Editar"></i></a>&nbsp;&nbsp;
                            <?php endif; ?>
                            <?php if($this->coTipoLogin==1 || $this->coTipoLogin==2) :?>
                                <a href="javascript:void(0);" for="perguntas" onclick="excluirRegistro(<?php echo $value["co_seq_perguntas"]; ?>, this);" style="color: #d9534f;" title="Excluir"><i class="icon-trash"></i></a>&nbsp;&nbsp;
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php $i++; ?>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>